import Foundation

@testable import NutritionLabelClassifier

let validTestCases: [Attribute: [String]] = [
    
    //MARK: - Energy
    
    .energy: [
        "'Regen ANG berdasarkan kebutuhan energi 21 50 kikal,",
        "'calories 220",
        "(8400 KJ) a day. saving of food contibutes to a daiy det 200 calories byam 2000 gA 45 pon gAle Alhi gh Zhn ial, )",
        "(8400 KJ) a day. saving of food contributes to a daily diet 200 calories by.= 2000 gA 45 pond gAle Ally he Zhen inal,)",
        "(calories 140",
        "*,' Calories",
        "*Aeren AKGberdasarkan kebutuhan energi 21 50 kkal.",
        ", Eneigy l Energie",
        "/ Energie / En'er2Fett I Vetten l Grassi l Grasas",
        "/ Energie / Ener",
        "/ Energie / EneriFett / Vetten / Grassi l Grasas",
        "/ Energie l Ener2Fett I Vetten l Grassi l Grasas",
        "/ food contributes to a daily diet. 2,000 calories",
        "/Energie /Ener",
        "0 % 2,000 calories",
        "0 % | Energy Engi",
        "0 %| Energyl Engi",
        "0% 2,000 calories",
        "0% Energy Enagi",
        "0% Energy Engi",
        "2,000 Calories diet.",
        "2,000 Calories diet.)",
        "Amount per serving Calories 190",
        "Brennwert Energi 735 kJ (177 kcal) 412 kJ (99 kcal)",
        "Calorfes 250 Calories from Fat 140",
        "Calorias por Gramo/Calories per Gram:",
        "Calorías/Calories: 2,000",
        "Calorias/Calories: 2,000 2.500",
        "Calorias/Calories:2,000 2.500",
        "Calories",
        "Calories / Calories 110",
        "Calories 100",
        "Calories 101 kcal",
        "Calories 120",
        "Calories 130 Fat calories 80",
        "Calories 140",
        "Calories 150",
        "Calories 150 Calories from Fat 25",
        "Calories 160",
        "Calories 180",
        "Calories 190",
        "Calories 210 Calories from Fat",
        "Calories 24 0",
        "Calories 240",
        "Calories 250 Calories from Fat 140",
        "Calories 270",
        "Calories 45",
        "Calories 70",
        "Calories 80 Calories from Fat 0",
        "Calories I'Calorias 150",
        "Calories from Fal 70",
        "Calories from Fal O CholesterDI <5mg 1% Sugats 70",
        "Calories from Fat 0",
        "Calories from Fat 0 Cholesterol <5mg 1% Sugars 7g",
        "Calories from Fat 120",
        "Calories from Fat 25",
        "Calories from Fat 70",
        "Calories from Fat 90",
        "Calories from Fat o",
        "Calories from Fat70",
        "Calories per gram:",
        "Calories per gran:",
        "Calories..",
        "Calories/Calorias",
        "Calories130 Fat calories 80",
        "Calories150 Calories from Fat 25",
        "Calories180",
        "Calories:",
        "Calories: 2,000",
        "Caloríias por Gramo/Calories per Gram:",
        "Calorles 240 Calories from Fat 120",
        "Caoras por Gramo Calories per Gram:",
        "Caoras por Gramo/ Calories per Gram:",
        "Cdwles I Calories 110",
        "ENERGY",
        "ENERGY / ENERGIE",
        "ETheryl dadLemak l Energy from Fat",
        "Ellergy/ Energie",
        "Energi Total / Total Energily",
        "Energi Total / Total Énergry",
        "Energi Total / Total Energy",
        "Energi Total / Total Énergy",
        "Energi Total Total Energsy",
        "Energi Total Total Energy",
        "Energi darf Lernak / En",
        "Energi dari Lemak /",
        "Energi dari Lemak / Energy from Fat",
        "Energi dari Lemak / Eners gy from Fat",
        "Energi dari Lemak / Eners y from Fat",
        "Energi dari Lemak/",
        "Energi dari Lemak/ Energy from Fat",
        "Energia Energinè vertèe/Energie/Energy",
        "Energia/Energinè verté Energie/Energy 344 kJ/84 kcal",
        "Energia/Energinè verte/Energie/Energy",
        "Energia/Energinèverte/Energie/Energy",
        "Energia/Energinèverte/Energie/Energy. 344 kJ/84 kcal",
        "Energie",
        "Energie / Energia / Valor energético",
        "Energie / énergie / energia",
        "Energie /Energia / Valor energético",
        "Energie /eneigie /energie /energy /energia /",
        "Energie /énergie /energie /energy /energia",
        "Energie energy, énergie /",
        "Energie energy, énergie/",
        "Energie l énergie l enerria",
        "Energie/énergie/energia",
        "Energie/énergie/energie/energy /energia",
        "Energl daTI Lemak l Energy from Fat",
        "Energl darf Lemak l Energy fmm Fat",
        "Energy",
        "Energy (52.4 Kcal)",
        "Energy (Energie",
        "Energy (kcal)",
        "Energy . ..",
        "Energy / 23 Lal",
        "Energy / 23 Lall",
        "Energy / 23 LlaJl",
        "Energy / 23 Llall",
        "Energy / 2a Lal",
        "Energy / 33UJI",
        "Energy / 33Ual",
        "Energy / Brennwert / Energi 735 kj (177 k(al)",
        "Energy / Energie",
        "Energy / Energie / Energie",
        "Energy / Energie / Energie / Energie / Energia / Valor energético",
        "Energy / Energie / Energie / Energie /Energia / Valor energético",
        "Energy / Énergie / Energie /Energie / Energia / Valor energético",
        "Energy / Energie Energie / Energie Energia Valor energético",
        "Energy / Energie Energie/Energie Energia/ Valor energético",
        "Energy / Valor energético",
        "Energy /Energie",
        "Energy /Energie / Energie / Energie / Energia / Valor energético",
        "Energy /Fnergie",
        "Energy /Valor energético",
        "Energy 116kcal 96kcal",
        "Energy 370 k¢al /1557 kj",
        "Energy 370 kcal / 1557 kj",
        "Energy 424 kJ",
        "Energy ai",
        "Energy alb",
        "Energy als",
        "Energy e1g1￿nerg1a (kj)",
        "Energy erylelEnergla (kj)",
        "Energy from Fat",
        "Energy from Fat (kcal)",
        "Energy value",
        "Energy,",
        "Energy, kcal",
        "Energy/ Enelgie",
        "Energy/ Energie",
        "Energy/ Énergie",
        "Energy/ Valor energético",
        "Energy/ aöuJl",
        "Energy/ asLiall",
        "Energy/ aslaJl",
        "Energy/ asllaJl",
        "Energy/ soul JI",
        "Energy/2 L",
        "Energy/23l",
        "Energy/2L",
        "Energy/3 b",
        "Energy/30",
        "Energy/3b",
        "Energy/49Lb",
        "Energy/¿illaJl.................",
        "Energy/Ene7gie 136 kJ 754 kj",
        "Energy/Energie/Energia (kJ)",
        "Energy/Tenaga/ANt",
        "Energy/Tenaga/Rt",
        "Energy/aillaJl................",
        "Energy/alb",
        "Energy/diLUI.......",
        "Energyl &iLWI",
        "EnergylJ Lb",
        "Fetbutahan energi anda mungkin lebamn? ( 2150 kkal.",
        "Heberihan energy an do meh yuh en an erg g/ 50 Midin endor.",
        "I Calories Calorías",
        "I ENERGY",
        "Ifood contributes to a daily diet. 2,000 calories",
        "Kebutuhan energi a:",
        "Kebutuhan energi ar",
        "Keturutan energi anda mungkin leblh tinggi atau lebih rendah.",
        "Pegen AKG berdasarkan kebutuhan energi 2150 kkal,",
        "Per Pot 116 Calories 2.2g Fat",
        "Per Pot 116 Calories 2.2g Fat its*iti:",
        "Percent daily values: Based upon a 2,000 Calories diet",
        "Percent dally values: Based upon a 2,000 Calories diet",
        "Rebutahan energi anda mungkin leban? ( 2150 kkal.",
        "Rebutuhan energi anda mungkini",
        "Tenaga Energy",
        "Tenagal Energy",
        "Valoare energetica",
        "Valoare energeticã",
        "Your daily intakes may be higher or lower depending on your energy needs.",
        "Zebutuhan energi anda mungkin i",
        "Zebutuhan energi anda mungkin k",
        "[(uaDUuDinluDu 80 nlaunaos)(Energy from ft 80 kcal)]",
        "[(waDUuDinluDu 80 nlaunaos)(Energy from ft 80 kcal)]",
        "[Energy/Energie/Energia (kJ)",
        "a serving of food contributes to a daily diet. 2,000 calories",
        "calories 130",
        "calories a",
        "contributes to a dailv diet 2 000 calories :",
        "contributes to a daily diet. 2 000 calories:",
        "contributes to a daily diet. 2,000 calories",
        "ie / Energie / Energia / Valor energético",
        "ie /Energie/Energia / Valor energético",
        "ie l Energia I Valor energetico",
        "ie l Energie / Energia / Valor energético",
        "ie l Energie l Energia I Valor energético",
        "ie l Energie l Energio I Valor energetico",
        "l Energie",
        "lower depending on your energy needs.",
        "may be higher or lower depending on your energy needs,",
        "persen AKG berdasarkan ketourtuhan eng perscruhan energi anda mungkin lean, ge / 2150 kkal.",
        "persen AKG berdasarkan knetourtuhan en perbcruhan energi anda mungkin fecan a / 2150 kkal.",
        "serving of food contributes to a daily diet. 2.000 calories a",
        "valor energético energi:",
        "wadonundnua 110 nlaunaos (Total energy 110 kcal)",
        "wavonundnua 110 nlaunaos (Total energy 110 kcal)",
        "y kcal",
    ],
    
    //MARK: - Protein
    .protein: [
        "( protéines /",
        "( protéines/",
        "(Palm, Sonnenblume), Wasser, mulgator.: Miono- und Dialyceride von Speisefettsauren; Saiz, Feuchthafemiel: Sorbito), pilanzliche Faser(Psyllium), sojaprotein, Reisstärke, Verdi-",
        "(Palm, Sonnenblume), Wasser, mulgator.: Mono- und Dialyceride von S peiserettsauren; Saiz, Feuchthalemiel: Sorbitol, pilanziche Fraser (Psyllium), sojaprotein, Reisstärke, Verdi-",
        "(palma, girasole), acqua, emulsionante: mono- e digliceridi degli acidi grassi, sale], umidificante: sorbitolo; fibra vegetale (psillio), proteine disoia, amido di riso, addensanti: gomma di",
        "*Protein/ Cale adle",
        "*Protein/ UsieyaJl",
        "*eMo:BalymaiProteina/Protein",
        "*elo BalymaiProteina/Protein",
        ", oIBatymailProteinalProtein",
        "-viviante vancomoni CM TaLLElI. 4 INGK&DIENTI Miscola di proteine (prot",
        ". Protein/ Proteines",
        "/ protein /",
        "0 % /Protein PFria",
        "0 % /Protein Print",
        "0% Protein 14g",
        "0% Protein 23g",
        "0% Protein/ Priat",
        "19 g 3,8 g 19% Proteine",
        "19 g | 3,8 g 19% Proteine",
        "2% Protein 12g",
        "3% Protein 15g",
        "65 Barrita alta en proteína, Envuelta en cho",
        "7 % Protein 5g",
        "7% Protein 2",
        "7% Protein 2g",
        "7% Protein 5g",
        "Aislado de Protein",
        "Aislado de Proteína",
        "Aislado de Proteína de Soja]), Caramelo [Edulcorante (Maltito!), Lecho Condens",
        "Aislado de Proteína de Soja], Caramelo [Edulcorante (Maltitol), Lecho Condens",
        "Aislado de Proteinp",
        "Cviviante vecomoni CMFOLLElI.  INGKEDIENTI Miscola di proteine (prot",
        "Eiweik/protéines/eiwitten/protein/proteine/proteinas/protein:",
        "Eiweiß",
        "Eiweiß / protéines/proteine",
        "Eiweiß/protéines/eiwitten/protein/proteine/ proteínas/protein:",
        "Eiweiß/protéines/proteine",
        "Fat 9 Carbohydrate4 • Protein4",
        "Fat 9 • Carbohydrate 4 • Protein 4",
        "Grosa Fat 9 • Carbohidratos/Carbohydrate. 4 • Proteína/Protein",
        "I Fru￿ I Proteinas",
        "INGREDIENT Miscela di protein (proteina",
        "INGREDIENTI Miscela di protein [proteina del latte,",
        "INGREDIENTI Miscela di proteine [proteina del latte,",
        "INGREDIENTI Miscela di proteine [proteina del latte, collagene idrol",
        "INGREDIENTI Miscela di proteino (oroteinz",
        "Ilium), protéines de",
        "L no Balyma/Proteina/Protein",
        "L4olBaltymaiiProteinalProtein",
        "N'AD'VIIE,'(ONTAINS MILK& MILK PRODUCTS Protein",
        "NICO?PROTEIN J'",
        "Nica PHRINE, PROTEIN S A N",
        "O% Protein14g",
        "PROTEIN",
        "PROTEIN / PROTEINES",
        "PROTEIN I PROTÉINES",
        "PROTEIN ISOLATE,",
        "PrOteIn/*]•￿Il Protefnas",
        "PrOteIn/o￿9?￿j1..............-...",
        "PrOteIn/￿9￿1/ Protelnas",
        "ProteIn/kn￿l>*jiI Protelnas",
        "ProteIn/￿]I￿1/ Prote(nas",
        "Protein",
        "Proteín",
        "Protein (0 g)",
        "Protein (g)",
        "Protein . Per",
        "Protein . ry>J",
        "Protein .Pei",
        "Protein /",
        "Protein / 00 all",
        "Protein / 00 gul",
        "Protein / 00 gull",
        "Protein / 00gll",
        "Protein / Proteina 2g",
        "Protein / Proteines / Eiwei& / Eiwitten I Proteine I Proteinas",
        "Protein / Proteines / EiweiE / Eiwitten I Proteine I Proteinas",
        "Protein / Proteines / EiweiE / Eiwitten I Proteine I Proteinas;",
        "Protein / Protéines / Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein / Protéines / Eiweiß Eiwitten / Proteine Proteínas",
        "Protein / Proteines / Eiwitten",
        "Protein / Protéines / Eiwitten",
        "Protein / Protéines /Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein / Protéines 0 g",
        "Protein / Protéines 3 g",
        "Protein / Proteines Eiwitten",
        "Protein / Protéines Eiwitten",
        "Protein / Protéines/ Ewitten",
        "Protein / Protéines/Eiweiß Eiwitten / Proteine Proteínas",
        "Protein / Protéines/Eiwitten",
        "Protein / iyuJwJI",
        "Protein / tile 1. ..............................................................................2.5 .",
        "Protein /0ugl",
        "Protein 0 c",
        "Protein 0 g",
        "Protein 0.7 g",
        "Protein 0c",
        "Protein 0g",
        "Protein 12g",
        "Protein 1g",
        "Protein 20g",
        "Protein 2g",
        "Protein 3 g",
        "Protein 30g",
        "Protein 3g",
        "Protein 4",
        "Protein 4g",
        "Protein 5g",
        "Protein 7g",
        "Protein <1g",
        "Protein Eiweiß",
        "Protein I Protéines 3 g",
        "Protein I Proteines l Eiwei@ l Eiwitten I Proteine I Proteinas",
        "Protein I Protéines l EiweiS l Etwitten I Proteine I Proteinas",
        "Protein I Proteines l FiweiE l Eiwrtten I Proteine I Proteinas",
        "Protein I Proteinesl EiweiE l Eiwitten I Proteine I Proteinas",
        "Protein I Protelnes / Elwltten",
        "Protein I Protélnes l Elwltten",
        "Protein Protéines / Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein l Elwei",
        "Protein/",
        "Protein/ 3ogell",
        "Protein/ 409 y",
        "Protein/ 80 gy",
        "Protein/ 80gy",
        "Protein/ 893 a",
        "Protein/ 931.2",
        "Protein/ Gog-all",
        "Protein/ Proteines",
        "Protein/ Protéines",
        "Protein/ Protéines / Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein/ ax",
        "Protein/ ￿ll19￿1",
        "Protein/,.J1/ Proteínas",
        "Protein/,xJl/ Proteínas",
        "Protein/30, J1/ Proteínas",
        "Protein/30i,J1/ Proteínas",
        "Protein/49 y",
        "Protein/93s2",
        "Protein/9x",
        "Protein/EE",
        "Protein/Jyy",
        "Protein/Proteinas 2g",
        "Protein/Proteínas 2g",
        "Protein/Protéines/Proteínas (g) 6.8",
        "Protein/Protéines/Proteínas (g) | 6.8",
        "Protein/TE T",
        "Protein/aiyul/ Proteínas",
        "Protein/ass-J1/ Proteínas",
        "Protein/g-ig-u1/ Proteinas",
        "Protein/gg-J1/ Proteínas",
        "Protein/gog-J1/ Proteínas",
        "Protein/gsg-Jl/ Proteínas",
        "Protein/gxigrul/ Proteínas",
        "Protein/ody",
        "Protein/taiyul/Proteínas",
        "Protein/us/spall/ Proteinas",
        "Protein/x/sull/ Proteínas",
        "Proteína / Protein 2g",
        "Proteína 2g",
        "Proteína/Protein",
        "Proteine",
        "Protéines",
        "Protéines / Eiweiss",
        "Proteines l Eiweiss",
        "Protéines/Eiweiss",
        "Proteinl",
        "Proteinl J",
        "Proteirn/ Proteines",
        "Proteln / Protéines O g",
        "Ptotein I Protéines l Eiwei@ l Eiwitten I Proteine I Proteinas",
        "Rolled oats, whey protein concentrate,",
        "Sno BalymaiProteina/Protein",
        "ÜsMu (Protein) 4 n. (g)",
        "WUshu (Protein) 4 n. (g)",
        "aromi, sale, colorante (caramello semplice)], edulcorante (maltitolo). burro di cacao, croccantini di soia con cacao [proteine isolate di soia, ami",
        "d INGREDIENTI Miscela di proteine [proteina del latte, coll",
        "danll/ Protein / Proteínas",
        "de Cacao, Copos de Soja (Aisiado de Proteina de",
        "de Cacao, Copos de Soja (Aislado de Proteina de Soja, Almidón de Taeloio",
        "de Cacao, Copos de Soja Aislado de Proteíná de Soja, Almidón de Teoloio",
        "de riz, épaississants : gomme de guar, gomme de caroube; sel, acidifiant : acide tartrique; arôme naturel. Peut contenir des traces de moutarde. SANS LACTOSE. SANS BI graisses et huiles végétales (palme, tournesol), eau, émulsifiant: mono- et diglycérides d'acides gras ; sel), humectant: sorbitol ; fibre végétale (psyllium), protéines de soja, amidon .Le produit",
        "de riz, épaississants : gomme de guar, gomme de caroube; sel, acidifiant : acide tartrique; arôme naturel.: Peut contenir des traces de moutarde. SANS LACTOSE. SANS BI [grasses et huiles végétales (palme, tournesol), eau, émulsifiant: mono- et diglycérides d'acides gras; sel), humectant: sorbitol ; fibre végétale (psyllium), protéines de soja, amidon . Le produit",
        "dean/l/ Protein / Proteínas",
        "eine [proteina del la",
        "eine [proteina del latte, collagene idrol\"",
        "elne [proteina del latte, collagene idrolizzato, proteine",
        "maltitojo). burro di cacao, croccantinl di sola con cacao [proteine isolate dl sola a",
        "milk protein isolate, fructose, apples",
        "milk protein isolate, fructose, apples,",
        "mtaiD gmsof protein,",
        "oiBaltymauProteinalProtein",
        "ontbijtgranen die gluten bevatten. I INGREDIENTI Miscela di proteine [proteina",
        "ontbijtgranen die gluten bevatten.H INGREDIENTI Miscela di proteine [proteina",
        "pinda's en ontbiitgranen die gluten bevatten. G INGREDIENTI Miscela di proteine (proteina del latte, collagene idro",
        "pinda's en ontbijtgranen die gluten bevatten. H INGREDIENTI Miscela di proteine [proteina del latte, collagene idrolizzato, proteine isolate o",
        "pinda's en ontbijtgranen die gluten bevatten. INGREDIENTI Miscela di proteine (proteina del latte, collagene idro",
        "pinda's en ontbijtgranen die gluten bevatten. M INGREDIENTI Miscela di proteine [proteina del latte, coll",
        "pinda's en ontbijtgranen die gluten bevatten. T INGREDIENTI Miscela di proteine [proteina del latte, collagene idrolizzato, proteine isolate o",
        "pinda's en ontbitgranen die gluten bevatten. M) INGREDIENTI Miscela di proteine [proteina del latte, coll",
        "protein, and al",
        "protein, and en",
        "proteinas",
        "proteínas",
        "pt iD gams of protein,",
        "sPaal/ Protein / Proteínas",
        "scholallymal/Proteina/Protein",
        "seaal/ Protein / Proteínas",
        "seho Gallymai/Proteina/Protein",
        "| Protein",
        
    ],
    
    //MARK: - carbohydrate
    .carbohydrate: [
        
    ]
]
