import Foundation

@testable import NutritionLabelClassifier

let validTestCases: [Attribute: [String]] = [
    
    //MARK: - Energy
    
    .energy: [
        "'Regen ANG berdasarkan kebutuhan energi 21 50 kikal,",
        "'calories 220",
        "(8400 KJ) a day. saving of food contibutes to a daiy det 200 calories byam 2000 gA 45 pon gAle Alhi gh Zhn ial, )",
        "(8400 KJ) a day. saving of food contributes to a daily diet 200 calories by.= 2000 gA 45 pond gAle Ally he Zhen inal,)",
        "(calories 140",
        "*,' Calories",
        "*Aeren AKGberdasarkan kebutuhan energi 21 50 kkal.",
        ", Eneigy l Energie",
        "/ Energie / En'er2Fett I Vetten l Grassi l Grasas",
        "/ Energie / Ener",
        "/ Energie / EneriFett / Vetten / Grassi l Grasas",
        "/ Energie l Ener2Fett I Vetten l Grassi l Grasas",
        "/ food contributes to a daily diet. 2,000 calories",
        "/Energie /Ener",
        "0 % 2,000 calories",
        "0 % | Energy Engi",
        "0 %| Energyl Engi",
        "0% 2,000 calories",
        "0% Energy Enagi",
        "0% Energy Engi",
        "2,000 Calories diet.",
        "2,000 Calories diet.)",
        "Amount per serving Calories 190",
        "Brennwert Energi 735 kJ (177 kcal) 412 kJ (99 kcal)",
        "Calorfes 250 Calories from Fat 140",
        "Calorias por Gramo/Calories per Gram:",
        "Calorías/Calories: 2,000",
        "Calorias/Calories: 2,000 2.500",
        "Calorias/Calories:2,000 2.500",
        "Calories",
        "Calories / Calories 110",
        "Calories 100",
        "Calories 101 kcal",
        "Calories 120",
        "Calories 130 Fat calories 80",
        "Calories 140",
        "Calories 150",
        "Calories 150 Calories from Fat 25",
        "Calories 160",
        "Calories 180",
        "Calories 190",
        "Calories 210 Calories from Fat",
        "Calories 24 0",
        "Calories 240",
        "Calories 250 Calories from Fat 140",
        "Calories 270",
        "Calories 45",
        "Calories 70",
        "Calories 80 Calories from Fat 0",
        "Calories I'Calorias 150",
        "Calories from Fal 70",
        "Calories from Fal O CholesterDI <5mg 1% Sugats 70",
        "Calories from Fat 0",
        "Calories from Fat 0 Cholesterol <5mg 1% Sugars 7g",
        "Calories from Fat 120",
        "Calories from Fat 25",
        "Calories from Fat 70",
        "Calories from Fat 90",
        "Calories from Fat o",
        "Calories from Fat70",
        "Calories per gram:",
        "Calories per gran:",
        "Calories..",
        "Calories/Calorias",
        "Calories130 Fat calories 80",
        "Calories150 Calories from Fat 25",
        "Calories180",
        "Calories:",
        "Calories: 2,000",
        "Caloríias por Gramo/Calories per Gram:",
        "Calorles 240 Calories from Fat 120",
        "Caoras por Gramo Calories per Gram:",
        "Caoras por Gramo/ Calories per Gram:",
        "Cdwles I Calories 110",
        "ENERGY",
        "ENERGY / ENERGIE",
        "ETheryl dadLemak l Energy from Fat",
        "Ellergy/ Energie",
        "Energi Total / Total Energily",
        "Energi Total / Total Énergry",
        "Energi Total / Total Energy",
        "Energi Total / Total Énergy",
        "Energi Total Total Energsy",
        "Energi Total Total Energy",
        "Energi darf Lernak / En",
        "Energi dari Lemak /",
        "Energi dari Lemak / Energy from Fat",
        "Energi dari Lemak / Eners gy from Fat",
        "Energi dari Lemak / Eners y from Fat",
        "Energi dari Lemak/",
        "Energi dari Lemak/ Energy from Fat",
        "Energia Energinè vertèe/Energie/Energy",
        "Energia/Energinè verté Energie/Energy 344 kJ/84 kcal",
        "Energia/Energinè verte/Energie/Energy",
        "Energia/Energinèverte/Energie/Energy",
        "Energia/Energinèverte/Energie/Energy. 344 kJ/84 kcal",
        "Energie",
        "Energie / Energia / Valor energético",
        "Energie / énergie / energia",
        "Energie /Energia / Valor energético",
        "Energie /eneigie /energie /energy /energia /",
        "Energie /énergie /energie /energy /energia",
        "Energie energy, énergie /",
        "Energie energy, énergie/",
        "Energie l énergie l enerria",
        "Energie/énergie/energia",
        "Energie/énergie/energie/energy /energia",
        "Energl daTI Lemak l Energy from Fat",
        "Energl darf Lemak l Energy fmm Fat",
        "Energy",
        "Energy (52.4 Kcal)",
        "Energy (Energie",
        "Energy (kcal)",
        "Energy . ..",
        "Energy / 23 Lal",
        "Energy / 23 Lall",
        "Energy / 23 LlaJl",
        "Energy / 23 Llall",
        "Energy / 2a Lal",
        "Energy / 33UJI",
        "Energy / 33Ual",
        "Energy / Brennwert / Energi 735 kj (177 k(al)",
        "Energy / Energie",
        "Energy / Energie / Energie",
        "Energy / Energie / Energie / Energie / Energia / Valor energético",
        "Energy / Energie / Energie / Energie /Energia / Valor energético",
        "Energy / Énergie / Energie /Energie / Energia / Valor energético",
        "Energy / Energie Energie / Energie Energia Valor energético",
        "Energy / Energie Energie/Energie Energia/ Valor energético",
        "Energy / Valor energético",
        "Energy /Energie",
        "Energy /Energie / Energie / Energie / Energia / Valor energético",
        "Energy /Fnergie",
        "Energy /Valor energético",
        "Energy 116kcal 96kcal",
        "Energy 370 k¢al /1557 kj",
        "Energy 370 kcal / 1557 kj",
        "Energy 424 kJ",
        "Energy ai",
        "Energy alb",
        "Energy als",
        "Energy e1g1￿nerg1a (kj)",
        "Energy erylelEnergla (kj)",
        "Energy from Fat",
        "Energy from Fat (kcal)",
        "Energy value",
        "Energy,",
        "Energy, kcal",
        "Energy/ Enelgie",
        "Energy/ Energie",
        "Energy/ Énergie",
        "Energy/ Valor energético",
        "Energy/ aöuJl",
        "Energy/ asLiall",
        "Energy/ aslaJl",
        "Energy/ asllaJl",
        "Energy/ soul JI",
        "Energy/2 L",
        "Energy/23l",
        "Energy/2L",
        "Energy/3 b",
        "Energy/30",
        "Energy/3b",
        "Energy/49Lb",
        "Energy/¿illaJl.................",
        "Energy/Ene7gie 136 kJ 754 kj",
        "Energy/Energie/Energia (kJ)",
        "Energy/Tenaga/ANt",
        "Energy/Tenaga/Rt",
        "Energy/aillaJl................",
        "Energy/alb",
        "Energy/diLUI.......",
        "Energyl &iLWI",
        "EnergylJ Lb",
        "Fetbutahan energi anda mungkin lebamn? ( 2150 kkal.",
        "Heberihan energy an do meh yuh en an erg g/ 50 Midin endor.",
        "I Calories Calorías",
        "I ENERGY",
        "Ifood contributes to a daily diet. 2,000 calories",
        "Kebutuhan energi a:",
        "Kebutuhan energi ar",
        "Keturutan energi anda mungkin leblh tinggi atau lebih rendah.",
        "Pegen AKG berdasarkan kebutuhan energi 2150 kkal,",
        "Per Pot 116 Calories 2.2g Fat",
        "Per Pot 116 Calories 2.2g Fat its*iti:",
        "Percent daily values: Based upon a 2,000 Calories diet",
        "Percent dally values: Based upon a 2,000 Calories diet",
        "Rebutahan energi anda mungkin leban? ( 2150 kkal.",
        "Rebutuhan energi anda mungkini",
        "Tenaga Energy",
        "Tenagal Energy",
        "Valoare energetica",
        "Valoare energeticã",
        "Your daily intakes may be higher or lower depending on your energy needs.",
        "Zebutuhan energi anda mungkin i",
        "Zebutuhan energi anda mungkin k",
        "[(uaDUuDinluDu 80 nlaunaos)(Energy from ft 80 kcal)]",
        "[(waDUuDinluDu 80 nlaunaos)(Energy from ft 80 kcal)]",
        "[Energy/Energie/Energia (kJ)",
        "a serving of food contributes to a daily diet. 2,000 calories",
        "calories 130",
        "calories a",
        "contributes to a dailv diet 2 000 calories :",
        "contributes to a daily diet. 2 000 calories:",
        "contributes to a daily diet. 2,000 calories",
        "ie / Energie / Energia / Valor energético",
        "ie /Energie/Energia / Valor energético",
        "ie l Energia I Valor energetico",
        "ie l Energie / Energia / Valor energético",
        "ie l Energie l Energia I Valor energético",
        "ie l Energie l Energio I Valor energetico",
        "l Energie",
        "lower depending on your energy needs.",
        "may be higher or lower depending on your energy needs,",
        "persen AKG berdasarkan ketourtuhan eng perscruhan energi anda mungkin lean, ge / 2150 kkal.",
        "persen AKG berdasarkan knetourtuhan en perbcruhan energi anda mungkin fecan a / 2150 kkal.",
        "serving of food contributes to a daily diet. 2.000 calories a",
        "valor energético energi:",
        "wadonundnua 110 nlaunaos (Total energy 110 kcal)",
        "wavonundnua 110 nlaunaos (Total energy 110 kcal)",
        "y kcal",
    ],
    
    //MARK: - Protein
    .protein: [
        "( protéines /",
        "( protéines/",
        "(Palm, Sonnenblume), Wasser, mulgator.: Miono- und Dialyceride von Speisefettsauren; Saiz, Feuchthafemiel: Sorbito), pilanzliche Faser(Psyllium), sojaprotein, Reisstärke, Verdi-",
        "(Palm, Sonnenblume), Wasser, mulgator.: Mono- und Dialyceride von S peiserettsauren; Saiz, Feuchthalemiel: Sorbitol, pilanziche Fraser (Psyllium), sojaprotein, Reisstärke, Verdi-",
        "(palma, girasole), acqua, emulsionante: mono- e digliceridi degli acidi grassi, sale], umidificante: sorbitolo; fibra vegetale (psillio), proteine disoia, amido di riso, addensanti: gomma di",
        "*Protein/ Cale adle",
        "*Protein/ UsieyaJl",
        "*eMo:BalymaiProteina/Protein",
        "*elo BalymaiProteina/Protein",
        ", oIBatymailProteinalProtein",
        "-viviante vancomoni CM TaLLElI. 4 INGK&DIENTI Miscola di proteine (prot",
        ". Protein/ Proteines",
        "/ protein /",
        "0 % /Protein PFria",
        "0 % /Protein Print",
        "0% Protein 14g",
        "0% Protein 23g",
        "0% Protein/ Priat",
        "19 g 3,8 g 19% Proteine",
        "19 g | 3,8 g 19% Proteine",
        "2% Protein 12g",
        "3% Protein 15g",
        "65 Barrita alta en proteína, Envuelta en cho",
        "7 % Protein 5g",
        "7% Protein 2",
        "7% Protein 2g",
        "7% Protein 5g",
        "Aislado de Protein",
        "Aislado de Proteína",
        "Aislado de Proteína de Soja]), Caramelo [Edulcorante (Maltito!), Lecho Condens",
        "Aislado de Proteína de Soja], Caramelo [Edulcorante (Maltitol), Lecho Condens",
        "Aislado de Proteinp",
        "Cviviante vecomoni CMFOLLElI.  INGKEDIENTI Miscola di proteine (prot",
        "Eiweik/protéines/eiwitten/protein/proteine/proteinas/protein:",
        "Eiweiß",
        "Eiweiß / protéines/proteine",
        "Eiweiß/protéines/eiwitten/protein/proteine/ proteínas/protein:",
        "Eiweiß/protéines/proteine",
        "Fat 9 Carbohydrate4 • Protein4",
        "Fat 9 • Carbohydrate 4 • Protein 4",
        "Grosa Fat 9 • Carbohidratos/Carbohydrate. 4 • Proteína/Protein",
        "I Fru￿ I Proteinas",
        "INGREDIENT Miscela di protein (proteina",
        "INGREDIENTI Miscela di protein [proteina del latte,",
        "INGREDIENTI Miscela di proteine [proteina del latte,",
        "INGREDIENTI Miscela di proteine [proteina del latte, collagene idrol",
        "INGREDIENTI Miscela di proteino (oroteinz",
        "Ilium), protéines de",
        "L no Balyma/Proteina/Protein",
        "L4olBaltymaiiProteinalProtein",
        "N'AD'VIIE,'(ONTAINS MILK& MILK PRODUCTS Protein",
        "NICO?PROTEIN J'",
        "Nica PHRINE, PROTEIN S A N",
        "O% Protein14g",
        "PROTEIN",
        "PROTEIN / PROTEINES",
        "PROTEIN I PROTÉINES",
        "PROTEIN ISOLATE,",
        "PrOteIn/*]•￿Il Protefnas",
        "PrOteIn/o￿9?￿j1..............-...",
        "PrOteIn/￿9￿1/ Protelnas",
        "ProteIn/kn￿l>*jiI Protelnas",
        "ProteIn/￿]I￿1/ Prote(nas",
        "Protein",
        "Proteín",
        "Protein (0 g)",
        "Protein (g)",
        "Protein . Per",
        "Protein . ry>J",
        "Protein .Pei",
        "Protein /",
        "Protein / 00 all",
        "Protein / 00 gul",
        "Protein / 00 gull",
        "Protein / 00gll",
        "Protein / Proteina 2g",
        "Protein / Proteines / Eiwei& / Eiwitten I Proteine I Proteinas",
        "Protein / Proteines / EiweiE / Eiwitten I Proteine I Proteinas",
        "Protein / Proteines / EiweiE / Eiwitten I Proteine I Proteinas;",
        "Protein / Protéines / Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein / Protéines / Eiweiß Eiwitten / Proteine Proteínas",
        "Protein / Proteines / Eiwitten",
        "Protein / Protéines / Eiwitten",
        "Protein / Protéines /Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein / Protéines 0 g",
        "Protein / Protéines 3 g",
        "Protein / Proteines Eiwitten",
        "Protein / Protéines Eiwitten",
        "Protein / Protéines/ Ewitten",
        "Protein / Protéines/Eiweiß Eiwitten / Proteine Proteínas",
        "Protein / Protéines/Eiwitten",
        "Protein / iyuJwJI",
        "Protein / tile 1. ..............................................................................2.5 .",
        "Protein /0ugl",
        "Protein 0 c",
        "Protein 0 g",
        "Protein 0.7 g",
        "Protein 0c",
        "Protein 0g",
        "Protein 12g",
        "Protein 1g",
        "Protein 20g",
        "Protein 2g",
        "Protein 3 g",
        "Protein 30g",
        "Protein 3g",
        "Protein 4",
        "Protein 4g",
        "Protein 5g",
        "Protein 7g",
        "Protein <1g",
        "Protein Eiweiß",
        "Protein I Protéines 3 g",
        "Protein I Proteines l Eiwei@ l Eiwitten I Proteine I Proteinas",
        "Protein I Protéines l EiweiS l Etwitten I Proteine I Proteinas",
        "Protein I Proteines l FiweiE l Eiwrtten I Proteine I Proteinas",
        "Protein I Proteinesl EiweiE l Eiwitten I Proteine I Proteinas",
        "Protein I Protelnes / Elwltten",
        "Protein I Protélnes l Elwltten",
        "Protein Protéines / Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein l Elwei",
        "Protein/",
        "Protein/ 3ogell",
        "Protein/ 409 y",
        "Protein/ 80 gy",
        "Protein/ 80gy",
        "Protein/ 893 a",
        "Protein/ 931.2",
        "Protein/ Gog-all",
        "Protein/ Proteines",
        "Protein/ Protéines",
        "Protein/ Protéines / Eiweiß / Eiwitten / Proteine / Proteínas",
        "Protein/ ax",
        "Protein/ ￿ll19￿1",
        "Protein/,.J1/ Proteínas",
        "Protein/,xJl/ Proteínas",
        "Protein/30, J1/ Proteínas",
        "Protein/30i,J1/ Proteínas",
        "Protein/49 y",
        "Protein/93s2",
        "Protein/9x",
        "Protein/EE",
        "Protein/Jyy",
        "Protein/Proteinas 2g",
        "Protein/Proteínas 2g",
        "Protein/Protéines/Proteínas (g) 6.8",
        "Protein/Protéines/Proteínas (g) | 6.8",
        "Protein/TE T",
        "Protein/aiyul/ Proteínas",
        "Protein/ass-J1/ Proteínas",
        "Protein/g-ig-u1/ Proteinas",
        "Protein/gg-J1/ Proteínas",
        "Protein/gog-J1/ Proteínas",
        "Protein/gsg-Jl/ Proteínas",
        "Protein/gxigrul/ Proteínas",
        "Protein/ody",
        "Protein/taiyul/Proteínas",
        "Protein/us/spall/ Proteinas",
        "Protein/x/sull/ Proteínas",
        "Proteína / Protein 2g",
        "Proteína 2g",
        "Proteína/Protein",
        "Proteine",
        "Protéines",
        "Protéines / Eiweiss",
        "Proteines l Eiweiss",
        "Protéines/Eiweiss",
        "Proteinl",
        "Proteinl J",
        "Proteirn/ Proteines",
        "Proteln / Protéines O g",
        "Ptotein I Protéines l Eiwei@ l Eiwitten I Proteine I Proteinas",
        "Rolled oats, whey protein concentrate,",
        "Sno BalymaiProteina/Protein",
        "ÜsMu (Protein) 4 n. (g)",
        "WUshu (Protein) 4 n. (g)",
        "aromi, sale, colorante (caramello semplice)], edulcorante (maltitolo). burro di cacao, croccantini di soia con cacao [proteine isolate di soia, ami",
        "d INGREDIENTI Miscela di proteine [proteina del latte, coll",
        "danll/ Protein / Proteínas",
        "de Cacao, Copos de Soja (Aisiado de Proteina de",
        "de Cacao, Copos de Soja (Aislado de Proteina de Soja, Almidón de Taeloio",
        "de Cacao, Copos de Soja Aislado de Proteíná de Soja, Almidón de Teoloio",
        "de riz, épaississants : gomme de guar, gomme de caroube; sel, acidifiant : acide tartrique; arôme naturel. Peut contenir des traces de moutarde. SANS LACTOSE. SANS BI graisses et huiles végétales (palme, tournesol), eau, émulsifiant: mono- et diglycérides d'acides gras ; sel), humectant: sorbitol ; fibre végétale (psyllium), protéines de soja, amidon .Le produit",
        "de riz, épaississants : gomme de guar, gomme de caroube; sel, acidifiant : acide tartrique; arôme naturel.: Peut contenir des traces de moutarde. SANS LACTOSE. SANS BI [grasses et huiles végétales (palme, tournesol), eau, émulsifiant: mono- et diglycérides d'acides gras; sel), humectant: sorbitol ; fibre végétale (psyllium), protéines de soja, amidon . Le produit",
        "dean/l/ Protein / Proteínas",
        "eine [proteina del la",
        "eine [proteina del latte, collagene idrol\"",
        "elne [proteina del latte, collagene idrolizzato, proteine",
        "maltitojo). burro di cacao, croccantinl di sola con cacao [proteine isolate dl sola a",
        "milk protein isolate, fructose, apples",
        "milk protein isolate, fructose, apples,",
        "mtaiD gmsof protein,",
        "oiBaltymauProteinalProtein",
        "ontbijtgranen die gluten bevatten. I INGREDIENTI Miscela di proteine [proteina",
        "ontbijtgranen die gluten bevatten.H INGREDIENTI Miscela di proteine [proteina",
        "pinda's en ontbiitgranen die gluten bevatten. G INGREDIENTI Miscela di proteine (proteina del latte, collagene idro",
        "pinda's en ontbijtgranen die gluten bevatten. H INGREDIENTI Miscela di proteine [proteina del latte, collagene idrolizzato, proteine isolate o",
        "pinda's en ontbijtgranen die gluten bevatten. INGREDIENTI Miscela di proteine (proteina del latte, collagene idro",
        "pinda's en ontbijtgranen die gluten bevatten. M INGREDIENTI Miscela di proteine [proteina del latte, coll",
        "pinda's en ontbijtgranen die gluten bevatten. T INGREDIENTI Miscela di proteine [proteina del latte, collagene idrolizzato, proteine isolate o",
        "pinda's en ontbitgranen die gluten bevatten. M) INGREDIENTI Miscela di proteine [proteina del latte, coll",
        "protein, and al",
        "protein, and en",
        "proteinas",
        "proteínas",
        "pt iD gams of protein,",
        "sPaal/ Protein / Proteínas",
        "scholallymal/Proteina/Protein",
        "seaal/ Protein / Proteínas",
        "seho Gallymai/Proteina/Protein",
        "| Protein",
        
    ],
    
    //MARK: - carbohydrate
    .carbohydrate: [
        "'otal Carbohydrates 0",
        "(ARBOHYDRATE",
        "(ARBOHYDRATE / GLU",
        "(Glucides/Hidratos de carbono (g) 75",
        "(Glycemic Carbohydrate/",
        "(Nariumcarbonate), nratürlches Aroma. Kann enbhalen Eruptiea",
        "(Narumcarbonale),.natürliches Aroma. Kano enthalen Eruptie.",
        "(Naruncarbonate), natirfiches Aroma. Kan enhalen E rants on ten",
        "(Natriumcarbonate), naturliches Aroma. Kann enthalteo, Erdofjs",
        "(Total carbohydrate) 3 n. (g)",
        "(arbohydrate / Kohlenhydri",
        "(dyoemk (art)ohydrate/",
        ")hydrates l Glucides l K￿1hydraten",
        "*worn a) saron de candi, poudre a lever (carbonates de sodia,",
        ",Carbohydrates / Glucides / Koolhydraten",
        ",Carbohydrates / Glucides 1 Koolhydraten",
        ",Carbohydrates / Glucldes / KcM)Ihydraten",
        ",carbohydrates l Glucldes / KC￿lhydraten",
        "-Carbohydrates / Glucides / Koolhydraten",
        "-Carbohydrates / Glucides 1 Koolhydraten",
        "-la￿>￿￿1/ Glucldesl Hldratos de carbono: 5.6 9",
        "0% Total Carbohydrate 19g 6%",
        "0% Total Carbohydrate 20g 7%",
        "0% Total Carbohydrates 9g 3",
        "1*40.3 sandisiroop, rismiddel (natriumcarbonaten), zeezout, kaneel), plantzardo, dia",
        "1*a0.j santdisiroop, rismiddel (natriumcarbonaten), zeezout, kaneel), olantzardog dia",
        "2% Carbohydrate Total/",
        "23 % Carbohydrate / Glucides 31 g",
        "23 % Carbohydrate l Glucides 31 g 10 % VitA",
        "9 % Total Carbohydrate1 g",
        "9 and SyU, craneseed lecithin), Easing agent (sodium carbonates), oR SpElled Eras as to sea salt, cinnamon), vegetable die (rapesel,",
        "9 ar SyU, crneseed lecithin), Fasing agent (sodium carbonates), sea salt, cinnamon), vegetabe die (rgeael,",
        "9% Total Carb <1g",
        "9% Total Carbohydrate 1g",
        "CARBOHYDRATE",
        "CARBOHYDRATE / GLUCIDES",
        "Caiboh1flralosTotaiesifoial Carbohydrats",
        "Caobohydrates / Gilucides / Koolhydraten",
        "Car phydrate g",
        "Carbo",
        "Carboh",
        "Carboh dese Lo",
        "CarbohYdrdte/￿IJ4*ty￿￿￿ Glutylesl Hldratos de carbono 5,6 9",
        "Carbohidiatos Totales 16g",
        "Carbohidratos Totales 16g",
        "Carbohidratos Totales/Total Carbohydrate",
        "Carbohy te/ Glucides 7.8 (y 43.) g",
        "Carbohydralel Glucides l Kohlenhydrate I loolhydraten I Carboidrati l Hidratos",
        "Carbohydrate",
        "Carbohydrate (g)",
        "Carbohydrate / Glucides / Kohlenhydrate / Koolhydraten / Carboidrati / Hidratos",
        "Carbohydrate / Glucides / Kohlenhydrate / Koolhydraten Carboidrati / Hidratos",
        "Carbohydrate / Glucides / Kohlenhydrate / loolhydraten I Carboidrati l Hidratos",
        "Carbohydrate / Glucides 24",
        "Carbohydrate / Glucides 24 g",
        "Carbohydrate / Glucides 28 g",
        "Carbohydrate / Glucides Kohlenhydrate / Koolhydraten / Carboidrati / Hidratos",
        "Carbohydrate / Kohlenhydrate",
        "Carbohydrate 18.1 g 15.1 g",
        "Carbohydratè 20.8 g",
        "Carbohydrate 27g",
        "Carbohydrate 4",
        "Carbohydrate l GPucides l Kohlenhydrate I loolhydraten I Carboidiati l Hidiatos",
        "Carbohydrate l Geu(ides l Kohlenhydrate i Ioolhydraten I Carboidrati l Hidratos",
        "Carbohydrate l Geucides l Kohlenhydrate I loolhydraten I Carboidrati l Hidratos",
        "Carbohydrate l Geuoides l Kohlenhydiate i loolhydraten I Carboidrati l Hidratos",
        "Carbohydrate(g)",
        "Carbohydrate(g) 42.0",
        "Carbohydrate/ 3l, napy-Sul",
        "Carbohydrate/ 3l,awbpy Sul",
        "Carbohydrate/ Glidcides 7. 8 g 43.) g",
        "Carbohydrate/ Gliicides 7.8 (y 43.5 g",
        "Carbohydrate/ Gloy,",
        "Carbohydrate/ Glucides 7.8 g",
        "Carbohydrate/ Sly MAy Su",
        "Carbohydrate/ Sly oH, SI",
        "Carbohydrate/ SlyApyu",
        "Carbohydrate/ al, op., sul/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/.",
        "Carbohydrate/31, **y SJ1/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/31,**y SJ/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/:l,op, sul/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/C/yuayS",
        "Carbohydrate/Cbsys",
        "Carbohydrate/Ci-sys",
        "Carbohydrate/O/yuayS",
        "Carbohydrate/Ohuays",
        "Carbohydrate/Olds a S",
        "Carbohydrate/Olesys",
        "Carbohydrate/Oly-syS",
        "Carbohydrate/Olydus eS",
        "Carbohydrate/Olyt2ys",
        "Carbohydrate/OlyusyS",
        "Carbohydrate/Shays",
        "Carbohydrate/a)y mays su1/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/a)y.mays.su/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/al,_,.99,S.J..",
        "Carbohydrate/al,_,99,SJl..",
        "Carbohydrate/al.w..y.u/Glucides/Hidratos de carbono",
        "Carbohydrate/always.sul/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/alwayy.sul/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/alws.yy.sul/ Glucides/ Hidratos de carbono",
        "Carbohydrate/kndl)W>4WI.....",
        "Carbohydrate/knilJ4a&>dAJI/ Glucldes/ Hldratos de carbono 5.6 9",
        "Carbohydrate/kn•lJ4￿$a￿jjI Glucldes/ Hldratos de carbono 5.6 9",
        "Carbohydrate/sI,...y, sul/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/sal,.**y su1/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/sl,**ysu1/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrate/sl,..oy, sJl/ Glucides/ Hidratos de carbono 5.6 g",
        "Carbohydrates",
        "Carbohydrates (12.5 g)",
        "Carbohydrates / - l)￿￿)&jI",
        "Carbohydrates / -04,49 «l",
        "Carbohydrates / -1, 4449 sil",
        "Carbohydrates / -L) 4449 sl",
        "Carbohydrates / =04,49 «il",
        "Carbohydrates / Gilucides / Koolhydraten",
        "Carbohydrates / Glucides / Koolhydraten",
        "Carbohydrates / ￿lJa&a3￿?£1l",
        "Carbohydrates / ￿lU￿*￿9￿?£1l",
        "Carbohydrates /=0449 <)",
        "Carbohydrates /=0449 <l",
        "Carbohydrates Glucides / Koolhydraten",
        "Carbohydratg",
        "Carbohydrdte '",
        "Carbohydrote",
        "Carboliydrate TotaV 1.2",
        "Carboliydrate Totav 1.2 g",
        "Carbondratos Totals /Total Carbohydrate",
        "Carbonidratos Totales/Total Carbohydrate",
        "Carbonydrate 4",
        "Carbotydrate l Geucides l Kohlenhydrate I loolhydraten I Carboidrati l Hidratos",
        "Carb•hydrat•s (12.5 9)",
        "Carsohydrate g",
        "Cartiobydrate C",
        "CartiobydrateCTs.",
        "Catbondraros Totales/Total Carbohydrate",
        "Catchydrates / Gaucides / Koolhydraten",
        "Cath1h￿lrate1￿IJ**trsj￿ Glucl3esl Hldratos de carbono S.6 9",
        "Cathhydrate/kn•lJ¥•p•llil Glucldesl Hldratos de caTbono S.6 g",
        "Clpdeys SU1 / Carbohydrate /",
        "Clyde os SU1 / Carbohydrate /",
        "Edratos de carbono",
        "Fat 9 Carbohydrate4 • Protein4",
        "Fat 9 • Carbohydrate 4 • Protein 4",
        "Glucide",
        "Glucide51 Kohlenh",
        "Glucide: Tes",
        "Glucides, Test",
        "Glucides, Total",
        "Glycaemic Carbohydrate/",
        "Glycemic Carbohydrate/",
        "Grosa Fat 9 • Carbohidratos/Carbohydrate. 4 • Proteína/Protein",
        "I CARBOHYDRATE",
        "IDtal Carbohydrate 23g",
        "J CaTbohydrate1Jw￿G1UthjesI HldfatosdecaTbono 5.69",
        "KAthohidrat I Carboh drate q,8 g",
        "Karbohidrat Total / Total Carbohy/rate",
        "Karbohidrat Total / Total Carbohydrate",
        "Karbohidrat Total / Total Carbohyirate",
        "Karbohidrat Total / Total Carbohyrate",
        "Karbohidrat Total Total Carbohy rate",
        "Karbohidrat Total Total Carbohy/rate",
        "Karbohldrat Totsl l Total CarbohydratE",
        "Kchlenhydrate / carbohydrate / glucides /",
        "Kohlenhydrate",
        "Kohlenhydrate / carbohydrate / glucides/",
        "Kohlenhydrate / glucides / carboidrati",
        "Kohlenhydrate / glucides / koolhydraten / catbohydrates /",
        "Kohlenhydrate glucides koolhydraten / carbohydrates",
        "Kohlenhydrate/glucides/carboidrati",
        "Kurbohidrat Total / Total Carbonyarate",
        "La Dohidratos/Carbohydrate",
        "LaDohidratos/Carbohydrate",
        "Lacchydrates / Gaucides / Koolhydraten",
        "Lolal Carbohydrate 17g",
        "Mariumhydrogencarbonat,\" Vanilleextrakt",
        "Natriumhydrogencarbonat,\" Vanilleextrakt",
        "Ndratos de carbono",
        "Nedratos de carbono",
        "NespondarylArgiavardenia/Carbohidrali./Carbohydrates0,0g",
        "O% Total Carbohydrate 2Cg 7%",
        "Outage SJ1 / Carbohydrate",
        "Oytay_ SJ1 / Carbohydrate",
        "Saturated Fat 0g 0% Total Carbohydrate 15g 5%",
        "TDtsJ Cartthydrate",
        "Tetal Carbohydrate 24g",
        "Tolal Carb. 34",
        "Totai Carbohydrate",
        "Total (arbohydrates (g)",
        "Total Caffaohydrate 19g e%",
        "Total Carb. 34g",
        "Total Carboh drate 4.2",
        "Total Carbohiidraie",
        "Total Carbohsidrate lg",
        "Total Carbohvdratas",
        "Total Carbohydrata 28g",
        "Total Carbohydrate",
        "Total Carbohydrate / Carbohidratos Totales 18g",
        "Total Carbohydrate 10 g",
        "Total Carbohydrate 16g",
        "Total Carbohydrate 17g",
        "Total Carbohydrate 19g",
        "Total Carbohydrate 1g",
        "Total Carbohydrate 21 g",
        "Total Carbohydrate 21 g 7 %",
        "Total Carbohydrate 21g",
        "Total Carbohydrate 21g 7%",
        "Total Carbohydrate 23g",
        "Total Carbohydrate 24g",
        "Total Carbohydrate 27 g",
        "Total Carbohydrate 27g",
        "Total Carbohydrate 28 g 9%",
        "Total Carbohydrate 28g",
        "Total Carbohydrate 33g",
        "Total Carbohydrate 34g",
        "Total Carbohydrate 39g",
        "Total Carbohydrate 62,2g/100g, 20,56g/32,7g; Trans fatty acids",
        "Total Carbohydrate 62,2g/lOOg, 20,56g132,7g; Trans fatty aads",
        "Total Carbohydrate 62,2gJl(M)9 2056g1317g; Trans fatty a(ids",
        "Total Carbohydrate 6g",
        "Total Carbohydrate/Carbohidrato Total 5g 2%",
        "Total Carbohydratelcarbohidrato Totsl 5 2 %",
        "Total Carbohydrates",
        "Total Carbohydrates (g)",
        "Total Carbohydrates 0 g",
        "Total Carbohydrates 23,4 g 9% ¿23,4",
        "Total Carbohydrates 23,4 g s",
        "Total Carbohydrates 23,4 gs",
        "Total Carbs.",
        "Total Carbs. 34",
        "Total Cathhydrate 21 g 8%",
        "Total carb. less than 1",
        "Total carb. less than 1g 0%",
        "Total carbohydrate/Jumlah karbohidrat/",
        "Total ca￿•hYdrate I Carbohidratos Totales18g",
        "Totsl carbohydratelJumlah karbohidratl",
        "Uespocdary Argiavardena /Carbohidrali /Carbohydrates 00g",
        "Unisroco, nismiddel (matriumcarbonaten), zeezout, kanean), ;",
        "Utta:/suwon._priddel/(atriumcarbonaten),.zeszout,kaneel),plantantigeder",
        "a[Ub￿s1￿D￿Ufi (Tol41 carbohydralo) 3 n. (g)",
        "airop de canci, poudre a lever (carbonates de sodium), sel de me:",
        "airop de canci, poudre à lever (carbonates de sodium), sel de me:",
        "ar) cdisroot zeriddel (natriumcarbonaten), zeezoot,",
        "bicarbonate, vanilla extract (Bourbon).",
        "carboidraii / hidraios de carbono / kulhydraL",
        "carboidrati hidratos de carbono / kulhydrat:",
        "carbonate acide de sodium,",
        "davon? Iidrutos de carbono / u6aráv8paKE,",
        "davon? Indratos de carbono / ubaráv8 paKE,",
        "de CarbGno",
        "de Carbono",
        "den sell a anisiroop, rismiddel (natriumcarbonaten), zeazout, kaneel), plantartead",
        "dnisroco, nismiddel (natriumcarbonaten), zeezout, kanean, ;",
        "enhydratel glucid& /(athidrati",
        "eswdtanyi.Arglarandenlal/Carbohidrali/Carbohydrates 0,0 g",
        "ew dary-Argiavandenial/Carbohidrali/Carbohydrates0,0g",
        "ewodary Argiavandena / Carbohidrali /Carbchydrates 0,0 g",
        "fia, palme), sucre, émulsifiant Amacartere tinlely srop de candi, poudre a lever INSOTEAEUENS, SA, DCuUICos tarine de Die, sucre, (lécithine de colza), (carbonates de sodium), ael de mat, margarine (praisse de palme. sucre caramelise en peurim",
        "fia, palme), sucre, émulsifiant Ana cart are striate)y strop de candi, poure a lever SING ONE ARE DENS, S A, DECulICos farine de Die, sucre, (lécithine de colza), (carbonates de sodium), al de met, margarine (praise de palme. sucre caramelis8 en pourin",
        "iuffl carbonates",
        "ium carbonates) sea • Cinnam￿), v•tk",
        "jop ed 1 serit /sodium carbonates), UNited wheat lone sugar malai de, rainle,.noes aroma g al ter sea salt, cinnamon), vegetable dis (rarel",
        "jop es t serit /sodium carbonates), Uced uhedloun sune malone naiule, noes Romsl alte sea sat, cimnamon), vegertable dis (raral",
        "karohidrat / Carbohydrate 4.8 g",
        "knndenii IcarbOh￿rats Icathhydrales O,O g",
        "lavaThleniai ICarbohhJratii Kathiydrales O,O g",
        "les wotany-Argiarandenlal/Carbohidrati/Carbohydrates 0,0 g",
        "lotal Carbohydrate 6g",
        "nNariuncarbonate), natürfiches Aroma. Kan entalen Erantiso",
        "orne) sarop de candi, poudre a lever (carbionates de sodia,",
        "otal Carbohydrate 16g",
        "otal Carbohydrates 0",
        "pEsa a anisiroop rismiddel (natriumcarbonaten), zeszout, kaneel), plantzartiead",
        "rbohldr•t Totsl l Total Carboh",
        "rbohydrates l Glucld8s / Koolhydraten",
        "smiddel (natrlumcarbonaten) zeezouL th),",
        "smiddel {natnumcarbonaten), zeezou(",
        "war) exis/root seriddel (atriumcarbonaten), zeezoot,",
        "ylkoliavandenii-lcarbohidrabi Icathhydrates O,O g",
        "| Glucide: Test",
        "| Glucides / Kohlenhydrate",
        "| karachidrat / Carbohydrate 4.8 g",
        "|Glucides / Kohlenhydrate",
    ],
    
    //MARK: - Gluten
    .gluten: [
        "-GLUTEN",
        ". gluten. I",
        "© Glutenfreier Tortilla-Wrap. Spezill formuliert für Menschen mit Glutenunverträglichkeit, ZUTATEN: Reis meh), Wasser, piflanzliche Margarine [pflanzliche Fette und Öle",
        "© Glutenfreier Tortilla-Wrap. Spezillformuliert für Menschen mit Glutenunverträglichkei t, ZUTATEN: Reis mehl, Wasser, piflanzliche Margarine [pflanzliche Fette und Öle",
        "© Tortilla-wrap sans gluten. Spécialement formulé pour les personnes souffrant d'une intolérance au gluten. INGRÉDIENTS : farine de riz, eau, margarine végétale",
        "Contains Soy, Gluten and",
        "Contains Soy, Gluten and Sulphite / cad u g as pea we",
        "Contains Soy, Gluten and Sulphite / cuadlug espe o",
        "Contains Soy, Gluten and Sulphite / culu d e le",
        "Contains Soy, Gluten and Sulphite / cutlass a le",
        "Contains Soyi Gluten and Sulphite",
        "Contains Soyi Gluten and Sulphite14*￿￿",
        "Gluten",
        "O GlutenhierTortilla-wrap. Speziell formuliertfilr MensclRftfflftGlthunvertra Ilch",
        "of milk, wheat (gluten). Bes",
        "trigo (Glúten)",
        "wheat (gluten). Bes",
        "whore soy, egg, fish and gluten products are also taco!",
        "whore soy, ogg, fish and gluten products ore asa taco!",
    ],
    
    //MARK: - Sugar
    .sugar: [
        "*a aneused sugar once Sade a , Mali let ian into a liane se",
        ",-of whlch sugars/ L* ' WI'L￿/",
        "- Of Which Sugars / Dont sucres / Davon Zucker / Waarvan suikers / di cui zuccheri /",
        "- Of Which Sugars / Dont sucres / Davon Zucker / Waarvan suikers / di cui zuccheri/",
        "- Of Which Sugars/Dontsucres / Davon Zucker I Waarvan suikers I di cui zuccheri I",
        "- SUGARS",
        "- SUGARS / SUCRE",
        "- SugarlGula/",
        "- Sugars",
        "- Sugars/ Siicres",
        "- Sugars/ Sucres",
        "- Suoars/ Sucres",
        "- of which sugars/ 44: sly Caul dams/",
        "- of which sugars/ L4n sly, Saul de ms/",
        "- of which sugars/ L4n sly, Suuull dems/",
        "- of which sugars/ Len aly-Saudi ans/",
        "- of which sugars/ Len sLy, Swell du was/",
        "- of which sugars/ Len sly, Sawl dews/",
        "- of which sugars/ Let al, Cudi aum/",
        "- sugars",
        "-L* whlch sugarsl ￿ ' Wl ¥￿5/",
        "-Of Which SUgarS/LéJ. d&Wi.... .-...-..--_",
        "-SUGARS",
        "-of which sugars/",
        "-of which sugars/ 41 aLy Swulf",
        "-of which sugars/ 41 alLy Swul",
        "-of which sugars/ 44t alyCudl dm/",
        "-of which sugars/ 4er alyCudi auw/",
        "-of which sugars/ Len sLy, Swudl duws/",
        "-of which sugars/ Lér aly-Sudi aws/",
        "-of which sugars/ Lfn sly, Swl duws/",
        "-of which sugars/ w. knidLuLdl",
        "-of which sugars/L& calySell da.m......oceseo/energetonesomeone-or-eno=",
        "-of which sugars/Lg calySell dtm.eesoeooesogpeoneoneoreoreoo=",
        "-of which sugars1",
        "-of whlch sugarsl w.",
        "-ofwhlch sugarsl w.",
        ". sugars / Zucker / socker / sukke[",
        ".0f￿1(h Sugars1￿ \"Wi 4",
        ".dont sucres/ de los cuales azucares",
        ".ofwhlch sugarslkn",
        "/which sugars / dont sucres",
        "1 0%7 cloyi5 kauriy cukristdin care zahanurlot which sugars 0,0 g Judas alumne",
        "10 a stryis kurt, cukris/din care zaharurilof which sugars 0,0 g Judas a nate",
        "11118nt3' Water, Sugars (Includin",
        "2% Sugars 18g",
        "2% Sugars18g",
        "40 7a lofts kany calkisdin care zahanuilof which sugars 0,0 g Judas al marta",
        "66% Salt, Sugar. OpuDnnur",
        "66% Salt, Sugar. apuDnnur",
        "A0%7 ckoyi5 kuriy cukrisidin care zahanurilot which sugars 0,0g Juodas afue",
        "A?IFn;-os/Sugars Og",
        "Amount per serving Saturated Fat Sugars Total Fat 3g Trans Fat 0g Sodium 380mg Incl. 0g Added",
        "Azúcares / Sugars 0g",
        "Ázúcares / Sugars 0g",
        "Azúcares. Sugars 0g",
        "Azúcares™ Sugars 0g",
        "Calories from Fat 0 Cholesterol <5mg 1% Sugars 7g",
        "Davon Zucker / Waarvan suikers/ di cui zuccheri /",
        "Davon Zucker /Waarvan suikers / di cui zuccheri /",
        "Davon Zucker Waarvan suikers / di cui zuccheri /",
        "Davon Zucker Waarvan suikers/ di cui zuccheri /",
        "De Ios cuales.. Azucares",
        "De l0s cuales: Azúcares",
        "De lOs cuales: Azúcares",
        "De los aja1￿. Azucares",
        "De los cuales.. Azucares",
        "De los cuales: Azucares",
        "De los cuales: Azúcares",
        "De105 cuales.. Azucares",
        "E 66% Salt, Sugar. @puDDur",
        "Gu/a/sugar",
        "Gula / Sugar",
        "Gula /sugar",
        "Gula I Sugar",
        "Gula Sugar",
        "Gula/ Sugar",
        "Gula/Sugar",
        "I Sugar",
        "I Sugars g",
        "IDgredieiits: Sugar 37 % ,",
        "In¥redients.' Sugar 37 % ,",
        "Incl. Addect Sugars",
        "Incluye 2g azucares anadidos",
        "Incluye 2g azúcares añadidos",
        "Ingiedlents.. Mllled corn, sugar. mall Ilavor,",
        "Ingredients: Sugar",
        "Ingredients: Sugar (Contains Sulphite), Soy Sauce Extr",
        "Ingredients: Sugar (Contains Sulphite), Soy Sauk",
        "Ingredients: Sugar (Contains Sulphite), Soy Saur4",
        "Ingredients: Sugar 37%, Water, Red",
        "Inp.lu¢e$12g AdtlE¢ SugarE 24",
        "Iwhich sugars / dont sucres",
        "Jumlah Gula Total Sugars 4,8 g",
        "M0 a stryfs kury cukris/din care zahanurilof which sugars 0,0 g Juodas a uae",
        "No es una fuente significativa de azucares anadidas.",
        "No es una fuente significativa de azúcares añadidas.",
        "OIWhich Sugars/Dontsucres l Davon Zucker I Waarvan suikers I di (ui zuccheri I",
        "Of Whi'ch Sugars/Dontsucres / Davon Zucker I Waarvan suikers I di cui zuccheri I",
        "Of Which Sugais l Dont sucres l Davon Zucker I Waarvan suikers I di cui zuccheri I",
        "Of Which Sugars / Dont sucres",
        "Of Which Sugars / Dont sucres / Davon Zucker / Waarvan suikers / di cui zuccheri /",
        "Of Which Sugars / Dont sucres / Davon Zucker / Waarvan suikers / di cui zuccheri/",
        "Of Which Sugars / Dont sucres Davon Zucker / Waarvan suikers / di cui zuccheri / di",
        "Of Which Sugars / Dont sucres Davon Zucker / Waarvan suikers / di cui zuccheri/ di",
        "Of Which Sugars l Dont sucres l Davon Zucker I Waarvan suikers I di cui zuccheri I",
        "Of Which Sugars l Dont sucres l Davon Zuckerl Waarvan suikers I di cui zuc(heri I",
        "Pa lofli kanu uikrosdin care zahanuilol which sugars 0,0g Juodas alynart",
        "S 66% Salt, Sugar. @puDDur",
        "SUGAR EGG WHITES.",
        "SUGARS",
        "SUGARS / SUCRE",
        "Siigars/ Sucres",
        "Sugar",
        "Sugar 8 g",
        "Sugar syrup (sugar,",
        "Sugar/Gula/ME",
        "Sugar81 Swes 28 g",
        "Sugars",
        "Sugars (g)",
        "Sugars / Sucres 17 g",
        "Sugars / Sucres 28 g",
        "Sugars / Sucres 30 g",
        "Sugars / aL, Sull",
        "Sugars / clay Sudl",
        "Sugars /. Wl",
        "Sugars /LdLu£al",
        "Sugars /aL,Sull",
        "Sugars /alySJl",
        "Sugars /clyySdl",
        "Sugars 0 a",
        "Sugars 1 g",
        "Sugars 13g",
        "Sugars 17g",
        "Sugars 19g",
        "Sugars 1g",
        "Sugars 20g",
        "Sugars 21 g",
        "Sugars 30g",
        "Sugars 7g",
        "Sugars 9g",
        "Sugars <1g",
        "Sugars I￿Sthan Ig",
        "Sugars hon",
        "Sugars less than 1 g",
        "Sugars less than 1g",
        "Sugars/ Sucres",
        "Sugarsy hon",
        "Sugary dea",
        "Sugary den",
        "Tolal Sugars 10g",
        "Total Sugar",
        "Total Sugars",
        "Total Sugars (",
        "Total Sugars / Azúcares Totales 0g",
        "Total Sugars / Azucares Totales Og",
        "Total Sugars 0 g",
        "Total Sugars 0g",
        "Total Sugars 1 g",
        "Total Sugars 10g",
        "Total Sugars 11g",
        "Total Sugars 14g",
        "Total Sugars 17g",
        "Total Sugars 1g",
        "Total Sugars 21 g",
        "Total Sugars 21g",
        "Total Sugars 9g",
        "Total Sugars Og",
        "Total Sugars/Azucares Total 2g",
        "Total Sugars/Azúcares Total 2g",
        "Total Sugars1 g",
        "Totsl Sugars",
        "T￿al sugars 09",
        "Ungredients: Sugar 37%, Water, Red",
        "Zucker / of which:",
        "ars / dont sucresj",
        "caramelised sugar powder (sugar, matadoxi,.",
        "caramelised sugar powder (sugar, matodexm  r",
        "davon Zucker",
        "davon Zucker / dont sucies / waatvan suikers / of which sugats /",
        "davon Zucker / dont sucres / di cui zuccheri",
        "davon Zucker dont sucres waarvan suikers of which",
        "davon Zucker/ dontSU￿/ di cui zuctheri",
        "dd which sugars / dont sucres,/",
        "dd wtich sugars / dont sucres,/",
        "de las cuales cat onush sugars / dont sucres /",
        "de los cuales catioausn sugars / dont sucres /",
        "di cui zuccheri / de los cuales azucares / heraf sukkerarter <0,5",
        "di cui zuccheri de los cuales azúcares / heraf sukkerarter <0,5 g",
        "din care zaharuri",
        "dont sucres / davon Zucker",
        "dont sucres/ de",
        "dont sucres/ de los cuales aZuca￿S",
        "dont sucres/ de los cuales azucares",
        "dont sucres/ de los cuales azúcares",
        "dont sucresl de los cuales azocares",
        "dont sucresl de los cuales azucares",
        "dontsucresl de los cuales azucares",
        "eww lerthiny caramelised sugar powder e (sugar, maltodectin), jnturd ftanuan a",
        "eww tertiny, caramelised sugar powder On o a adders (sugar, maltodectio), intured fan an a",
        "eww tertiny, caramelised sugar powder o a adders (sugar, maltodectin), intured fan no a",
        "gredients: Sugar 370/0,",
        "jop ed 1 serit /sodium carbonates), UNited wheat lone sugar malai de, rainle,.noes aroma g al ter sea salt, cinnamon), vegetable dis (rarel",
        "lj'm Ikrylis kuriu cUkrU￿din care zahaNnJof which sugars O,O g",
        "los cuales azúcares",
        "of Ivhlch sugars I dont sucres,I",
        "of which Sugar (g)",
        "of which Sugars/ 56 J sze",
        "of which Sugars/ Cob S. J1 gis",
        "of which Sugars/ OL\" ais",
        "of which Sugars/ Ou S# lais",
        "of which Sugars/ OuS.# luis",
        "of which Sugars/ aunt",
        "of which Sugars/ aunts",
        "of which Sugars/5tJ sze",
        "of which Sugars/Cb S.J1 gis",
        "of which Sugars/OL\" aia",
        "of which Sugars/ObJ Le",
        "of which Sugars/Obl 4",
        "of which sugars",
        "of which sugars / dont sucres /",
        "of which sugars / dont sucres/",
        "of which sugars dont sucres /",
        "of which sugars/",
        "of which total sugar/dont",
        "of whith totsl sugarldont",
        "of whkh totsl sugarldont",
        "of whlch sugars I dont sucres /",
        "of ￿1th sugars",
        "ol which sugars",
        "ot Aihich sugars",
        "ougars / de los cuales azúcares",
        "rt cultures), Strdwbffj (10Yo), Sugar",
        "stal Sugars g",
        "sucres/dos quais açúcares (g) 47.3",
        "sucres/dos quais açúcares (g) 473",
        "sugar3",
        "sugars",
        "sugars / de los cuales azúcares",
        "thona (Sugars) 2 n. (g)",
        "uf which Sigars b a o",
        "utal Sugars g",
        "waarvan suikers",
        "ww lerthiny caramelised sugar powder e (sugar, maltodectin), jnturd ftanuan a",
        "yoguit cultures), Strawberry (10%), Sugar AbarAy",
        "yogurt cultures), Strawberry (10%), Sugar AbarAy",
        "• Of Which Sugars / Dont sucres / Davon Zucker (Waarvan suikers / di cui zuccheri /",
        "• Of Which Sugars / Dont sucres / Davon Zucker IWaarvan suikers / di cui zuccheri /",
        "• Sugars/ Sucres",
        "• davon Zucker",
        "• sugars/ Zucker / socker sukker",
    ],
    
    //MARK: - Added Sugars
    .addedSugar: [
        "- Includes 0 g Added Sugars",
        "-Includes 0 g Added Sugars",
        "0 g Added Sugars",
        "1g Added Sugars",
        "Added Sugars g",
        "Incl 17g Added Sugars 34%",
        "Incl. 10g Added Sugars 19% We're here to help.",
        "Incl. Added Sugars 12g",
        "Incl. Og Added Sugars",
        "Incl17g Added Sugars 34%",
        "Includes 0 g Added Sugars",
        "Includes 0g Added Sugars",
        "Includes 12g Added Sugars 24%",
        "Includes 15,63 grams",
        "Includes 16g Added Sugars",
        "Includes 2g Added Sugars/",
        "Includes 7g Added Sugars 14%",
        "Includes 8g Added Sugars",
        "Includes < 1 g Added Sugars",
        "Includes Og Added Sugars",
        "Includes Og Added Sugars 00/0",
        "Indudes 8g Added Sugars",
        "Inelud8s Og Added Sugars",
        "Of Which Added Sugar (11.8 g)",
        "Ssua pla fadded sugar",
        "Sue pl pa F added sugar",
        "of added sugar",
    ],
    
    //MARK: - Polyols
    .polyols: [
        "- Of Which Polyols / Dont polyols / Davon mehrwertige Alkohole I Waatvan polyolen I",
        "- Of Which Polyols l Dont polyols l Davon mehrwertige Alkohole I Waatvan polyolen I",
        "- Of kllhich Polyols l Dont polyols / Davon mehrwertige Alkohole I Waarvan polyolen I",
        ". Of Which Polyols l Dont polyols l Davon Meh￿ertIge Alkohole I Waarvan polyolen I",
        "0f Which Polyols / Dont polyols / Davon mehrwertige Alkohole / Waarvan polyolen/",
        "O! Iyhich Polyolsl Dont polyols l Davon mehrwertige Alkohole I Waarvan polyolen I",
        "O! Which Polyols l Dont polyols l Davon Meh￿ertIge Alkohole I Waarvan polyolen I",
        "Of Which Polyols / Dont polyols",
        "Of Which Polyols / Dont polyols / Davon",
        "Of Which Polyols / Dont polyols / Davon mehrwertige Alkohole / Waarvan polyolen /",
        "Of Which Polyols / Dont polyols / Davon mehrwertige Alkohole / Waarvan polyolen/",
        "Of Which Polyols / Dont polyols Davon mehrwertige Alkohole / Waarvan polyolen /",
        "Of Which Polyols / Dont polyols/ Davon mehrwertige Alkohole / Waarvan polyolen /",
        "Of Which Polyols l Dont polyols l Davon Meh￿ertIge Alkohole I Waarvan polyolen I",
        "Of Which Polyols l Dont polyols l Davon mehrwertige Alkohole I Waarvan polyolen I",
        "Of Which Polyols/Dont polyols / Davon",
        "Of Which Polyols/Dont polyols Davon mehrwertige Alkohole / Waarvan polyolen/",
        "di cdi polioli l De los cuales: Polial(oholes",
        "di cui polioli / De los cuales: Polial(oholes",
        "di cui polioli / De los cuales: Polialcoholes",
        "di cui polioli / De los cuales: Polialçoholes",
        "di cui polioli l De los cuales. Polialcoholes",
        "di cui polioli l De los cuales: Polialcoholes",
        "di cui polioli l De los cuales: Polialroholes",
        "di cui polioli'/ De los cuales: Polialcoholes",
        "di cui polioli/ De los cuales:",
        "• Of Which Polyols / Dont polyols / Davon mehrwertige Alkohole 1Waarvan polyolen/",
        "• Of Which Polyols / Dont polyols / Davon mehrwertige Alkohole Waarvan polyolen /",
    ],
    
    //MARK: - Starch
    .starch: [
        "of which starch",
    ],
    
    //MARK: - Dietary Fibre
    .dietaryFibre: [
        "%adSkadulinés medziagos Fibra/Fiber",
        "%unadSkaidulinés medziagos/Fibra Fiber",
        "',iik/skaidulinés medziagoslFibraFiber",
        "'bra Qielélica l Dietary Fiber1g",
        "(palma, girasole), acqua, emulsionante: mono- e digliceridi degli acidi grassi, sale], umidificante: sorbitolo; fibra vegetale (psillio), proteine disoia, amido di riso, addensanti: gomma di",
        "(taire* /fibra dietética* (g)",
        ",,]￿i,Ska1du1inés medziago&FibraFiber",
        ",irniklskaidulinés medziagoslFibralFiber",
        "- Dietary Fibre/",
        "0% Dietary Fiber 0g",
        "23 % Dietary Fiber Og",
        "34 g 6,9 g 10% Fibre",
        "A SOURCE OF FIBRE",
        "Ballaststoffe",
        "Ballaststoffe / fibres alimentaires / fibre",
        "Ballaststottest",
        "Cetary fiore:/ Fibres alimentaires /",
        "Cezary fitre / Fibres alimentaires /",
        "D*tiry Fiber",
        "D4&t¥tyFiber59",
        "DIETARY FIBRE",
        "DIEtARY FIBRE",
        "Didary flbre / Fibres alimentslres /",
        "Dieiary Fiber",
        "Dielaiy Fiber 5g",
        "Dielary Fiber",
        "Dielary ibre / Fibres alimentaires /",
        "Dienary Fiber 5g",
        "Dieta Fiber",
        "Dietan Fiber",
        "Dietary Ffibre",
        "Dietary Fiber",
        "Dietary Fiber (0.27 g)",
        "Dietary Fiber / Fibra Dietética 1g",
        "Dietary Fiber / Fibra Dietética lg",
        "Dietary Fiber 0",
        "Dietary Fiber 0 g",
        "Dietary Fiber 0g",
        "Dietary Fiber 1g",
        "Dietary Fiber 2g",
        "Dietary Fiber 3g",
        "Dietary Fiber 48",
        "Dietary Fiber 4g",
        "Dietary Fiber 5g",
        "Dietary Fiber 6g",
        "Dietary Fiber 7g",
        "Dietary Fiber < 1 g",
        "Dietary Fiber <1 g",
        "Dietary Fiber <1g",
        "Dietary Fiber Og",
        "Dietary Fiber Og ¢",
        "Dietary Fiber less than 1g",
        "Dietary Fiber less than lg 391,",
        "Dietary Fiber/Fibra Dietética 2g",
        "Dietary Fiber6g",
        "Dietary Fibers",
        "Dietary Fibre",
        "Dietary Fibre/",
        "Dietary fiber 0.2 g",
        "Dietary fibre / Fibres alimentaires /",
        "Dietary fibre / Fibres alimentaires/",
        "Dietary fibre*/fibre alimen-",
        "Dietary fibre/Serat makanan/ 1:. FF AIR Aft",
        "Dietary fibre/Serat makanan/1t. FFI A0C AfE",
        "Dietary fibrelserat makananlft￿I1X .",
        "Dietary flbre / Fibres alimentalres /",
        "Dietsry flbre l Fibres allmentaires I",
        "Dletary Fiber",
        "FIBRE",
        "FIbre/4•1￿ll Flbres allmentslresl Flbra allmentsrla O g",
        "FIbre/￿Il￿1 JLfyI/ Flbres allmentairesl Fibra alimentsria o g",
        "FIbre/￿Il￿AJl",
        "Fbra Dietética/Dietary Fiber",
        "Fiber",
        "Fiber 0g",
        "Fibra DieieticiDietary Fiber",
        "Fibra Dietética / D.etary Fiber 1g",
        "Fibra Dietética/Dietary Fiber",
        "Fibre",
        "Fibre (oligofructose), Glucose-fructose syrup,",
        "Fibre / Fibres 1 g",
        "Fibre / Fibres 2 g",
        "Fibre/ &kul JL/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/ 4èd'l&ill iLJ¥I",
        "Fibre/ A51AJI JLM/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/ Fibres 2 g",
        "Fibre/ Juf",
        "Fibre/ L3&ll Jilx/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/ a, kul Jut/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/&ulacai JLt/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/3ul",
        "Fibre/ANTeD SLUXI",
        "Fibre/ASED) CLX",
        "Fibre/ASIAN)SLUXI",
        "Fibre/ASSED) CLUM",
        "Fibre/ASTA ELJXI",
        "Fibre/ATe SLUXI",
        "Fibre/A_51All JLM/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/Auilall aiuy/ Fibres alimentaires/ Fibra alimentaria 0 g",
        "Fibre/Aull-allaiuy/Fibresalimentaires/Fibraalimentaria0g",
        "Fibre/Aust&cal JUt/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/Gul",
        "Fibre/JLJI",
        "Fibre/Jul",
        "Fibre/L'i&iJl JLfyI/ Flbres alimentalresl Flbrd alimentaria o g",
        "Fibre/LI&ll Jilx/ Fibres alimentaires/ Fibra alimentaria",
        "Fibre/O",
        "Fibre/Ol",
        "Fibre/äWi",
        "Fibre/älall uuutt/ Fibres alimentaires/ Fibra alimentaria 0 g",
        "Fibre/augaeal aiy/ Fibres alimentaires/ Fibra alimentaria 0 g",
        "Fibre/augure-all aiLy/ Fibres alimentaires/ Fibra alimentaria 0 g",
        "Fibre/aul",
        "Fibre/äul",
        "Fibre/aul&all alth/ Fibres alimentaires/ Fibra alimentaria 0 g",
        "Fibre/sWi",
        "Fibre/ul",
        "Fibre/￿Il￿1 dLfyI/ Flbres allmentairesl Fibra alimentsria o g",
        "Fibre1￿LI1",
        "Fibrel4tsuI",
        "Fibreo d",
        "Fibres",
        "Fibres alimentaires / Ballaststoffe",
        "Fibres alimentaires l Ballaststoffe",
        "Fira Dietética / D.etary Fiber 1 g",
        "Fires alimentaires/Ballaststoffe",
        "Flbre/4Ji&ath J4M/ Flbres allmentslres/ Fibra allrnentsria",
        "Fora Dietética/Dietary Fiber",
        "Ftse l fibres O g",
        "J3LSi / Fibre / Fibra",
        "JuST / Fibre / Fibra",
        "O% DEtary Fiber less than Ig 4%",
        "O￿tsry fibre / fibres limentsires /",
        "Saw ad Skadulines medziagos/Fibra/Fiber",
        "Sent SKaiulinés metiziagos/Fibra/Fiber",
        "Sentk SKaidulinés metiziagos IFibra/Fiber",
        "Serat Pangan / Dietary Fiber",
        "Serat Pangan Dietary Fiber",
        "Serat Pangan/ Dietary Fiber",
        "Voedingsvezel",
        "audi / Fibre / Fibra",
        "de riz, épaississants : gomme de guar, gomme de caroube; sel, acidifiant : acide tartrique; arôme naturel. Peut contenir des traces de moutarde. SANS LACTOSE. SANS BI graisses et huiles végétales (palme, tournesol), eau, émulsifiant: mono- et diglycérides d'acides gras ; sel), humectant: sorbitol ; fibre végétale (psyllium), protéines de soja, amidon .Le produit",
        "de riz, épaississants : gomme de guar, gomme de caroube; sel, acidifiant : acide tartrique; arôme naturel.: Peut contenir des traces de moutarde. SANS LACTOSE. SANS BI [grasses et huiles végétales (palme, tournesol), eau, émulsifiant: mono- et diglycérides d'acides gras; sel), humectant: sorbitol ; fibre végétale (psyllium), protéines de soja, amidon . Le produit",
        "ectant: sorbitol. fibre vé",
        "fibre l Fth￿s alimentalres I",
        "fibre/Ju",
        "i grassi. salel, umidificante: soibitolo, fibra ve&NZA LATtO",
        "laundSkaidulines medziagos/Fibra/Fiber",
        "libre",
        "libron",
        "loons (Dietary fiber) 2 n. (g)",
        "loowns (Dietary fiber) 2 n. (g)",
        "of which Dietary Fibre (g)",
        "ora Dietética / Dietary Fiber 1 g",
        "ora Dietética / Dietary Fiber 1g",
        "oudi / Fibre / Fibra",
        "ststoffe/fi\"bres alim￿￿1￿/ fibre",
    ],
    
    //MARK: - Soluble Fibre
    .solubleFibre: [
        "- Soluble fibre/Serat boleh laruv7h•titt",
        "Soluble Fiber 1g",
        "Soluble Fiber 2g",
        "Soluble Fiber Ig",
        "Soluble Fibre (g)",
        "Soluble fibre/Serat boleh larut/K PER ME AIL AE",
        "Soluble fibre/Serat boleh larut/zK PE NE AIC AE",
    ],
    
    //MARK: - Insoluble Fibre
    .insolubleFibre: [
        "Insoluble Fiber 2g",
        "Insoluble Fiber 3g",
        "Insoluble Fibre (g)",
        "Insoluble fibre/Serat tidak boleh larut/",
        "Insoluble fibre/Serat tidak boleh laruv",
    ],
    
    //MARK: - Fat
    .fat: [
        "¡udurionun (Total fat) 9 n. (g)",
        "',%l Total Fat Og",
        "(GB) Mild white Cheddar cheese, 35 % total fat, 48% f.l.d.m.,",
        "(GB) Mild white Cheddar cheese, 35% total fat, 48% f.i.d.m.,",
        "(Jumlah Lemak | Total Fat",
        "(Jumlah Lemak| Total Fat",
        "(Modified starch), Milkfat, Beef gelatin, Sweetener (Sucralosel), Fret real g",
        "(Palm, Sonnenblume), Wasser, mulgator.: Miono- und Dialyceride von Speisefettsauren; Saiz, Feuchthafemiel: Sorbito), pilanzliche Faser(Psyllium), sojaprotein, Reisstärke, Verdi-",
        "(lodiied starch), Milkfat, Beef gelatin, Sweetener (Sucralosel), Frot reag",
        "(palma, girasole), acqua, emulsionante: mono- e digliceridi degli acidi grassi, sale], umidificante: sorbitolo; fibra vegetale (psillio), proteine disoia, amido di riso, addensanti: gomma di",
        ",V&sat Fat Menos de/Less than 2",
        "- s&Urat￿ fatty acids/Lemak tepul",
        ". Jgtsthl Fatl (￿aS",
        ". te Fettsauren",
        "/ Energie / En'er2Fett I Vetten l Grassi l Grasas",
        "/ Energie / EneriFett / Vetten / Grassi l Grasas",
        "/ Energie l Ener2Fett I Vetten l Grassi l Grasas",
        "0 % Total Fat Boule ta",
        "0% Total Fat Boale ta",
        "3va all / Fat / Grasas",
        "3yauJl / Fat / Grasas",
        "© Glutenfreier Tortilla-Wrap. Spezill formuliert für Menschen mit Glutenunverträglichkeit, ZUTATEN: Reis meh), Wasser, piflanzliche Margarine [pflanzliche Fette und Öle",
        "© Glutenfreier Tortilla-Wrap. Spezillformuliert für Menschen mit Glutenunverträglichkei t, ZUTATEN: Reis mehl, Wasser, piflanzliche Margarine [pflanzliche Fette und Öle",
        "© Tortilla-wrap senza glutine. Specificamente formulato per persone intolleranti al glutine. INGREDIENT: Farina di riso, acqua, margarina vegetale [grassi e oli vegetali",
        "© Tortilla-wrap senza glutine. Specificamente formulato per persone intolleranti al glutine. INGREDIENTI: Farina di riso, acqua, margarina vegetale [grassi e oli vegetali",
        "® Ingredients: Beef meat, beef fat, nitrite salt (salt, preservative: sodium nitite),",
        "ADDS A TRIVIAL AMOUNT OF FAT.",
        "Butterreinfett, Molkenerzeugnis, Kakaomasse, Emulgalos",
        "Butterrelnfett, Molkenerzeugnis, Kaka0in3sse, Erriul",
        "Cacries from Fat 0",
        "Calorfes 250 Calories from Fat 140",
        "Calories 130 Fat calories 80",
        "Calories 150 Calories from Fat 25",
        "Calories 210 Calories from Fat",
        "Calories 250 Calories from Fat 140",
        "Calories 80 Calories from Fat 0",
        "Calories from Fat 0",
        "Calories from Fat 0 Cholesterol <5mg 1% Sugars 7g",
        "Calories from Fat 120",
        "Calories from Fat 25",
        "Calories from Fat 70",
        "Calories from Fat 90",
        "Calories from Fat o",
        "Calories from Fat70",
        "Calories130 Fat calories 80",
        "Calories150 Calories from Fat 25",
        "Calorles 240 Calories from Fat 120",
        "Clories from Fat O S•dlK• 50fflg",
        "Deaall/ Fat / Grasas",
        "Due all / Fat / Grasas",
        "ERANS. KONEA YOGURT (CULTURED PASTEURIZED NONFAT MILK LIVE AND ACTIVE CULLIE,",
        "ETheigy from Fat (kcal)",
        "ETheryl dadLemak l Energy from Fat",
        "Energi dari Lemak / Energy from Fat",
        "Energi dari Lemak / Eners gy from Fat",
        "Energi dari Lemak / Eners y from Fat",
        "Energi dari Lemak/ Energy from Fat",
        "Energl daTI Lemak l Energy from Fat",
        "Energl darf Lemak l Energy fmm Fat",
        "Energl darl Lemakl Enertyfrom Fat",
        "Energry from Fat",
        "Energy from Fat",
        "Energy from Fat (kcal)",
        "FAI",
        "FAT",
        "FAT PER SERVING",
        "FAT, TOTAL",
        "FAT, TOTAL / GRAISSE, TOTAL",
        "FAT, TOTAL / GRAISSE, TOTAL 6.8g",
        "FATPERSIIWKG",
        "Fat",
        "Fat (0 g)",
        "Fat (O g)",
        "Fat (g)",
        "Fat / Linides / Vetten",
        "Fat / Lip,'des / Vetten",
        "Fat / Liphles / Vetten",
        "Fat / Lipides / Vetten",
        "Fat / Lipides / Vetten ',",
        "Fat / Lipides 0 g",
        "Fat / Lipides 15 g",
        "Fat / Lipides O g",
        "Fat / Matières Grasses / Fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses / Fett / Vetten / Grassi Grasas",
        "Fat / Matières Grasses / Fett Vetten / Grassi / Grasas",
        "Fat / Matières Grasses / fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses /Fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses /fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses Fett / Vetten / Grassi / Grasas",
        "Fat /Matières Grasses /Fett / Vetten / Grassi / Grasas",
        "Fat /Matières Grasses /Fett Vetten / Grassi / Grasas",
        "Fat 0g",
        "Fat 9",
        "Fat 9 Carbohydrate4 • Protein4",
        "Fat 9 • Carbohydrate 4 • Protein 4",
        "Fat Cal 60",
        "Fat I",
        "Fat l L4xdeS 4.5 g",
        "Fat l Lipides 15 g",
        "Fat, Total",
        "Fat, total",
        "Fat/",
        "Fat/ Lipides / Vetten",
        "Fat/ a",
        "Fat/&lP' ....................",
        "Fat/--›",
        "Fat/-›",
        "Fat/.-d3",
        "Fat/...43",
        "Fat/39.03 ................................",
        "Fat/Zlatieres Grasses",
        "Fat/aa",
        "Fat/e-s",
        "Fat/ee",
        "Fat/fvaJ",
        "Fat/j9... ................................",
        "Fat/o-S",
        "Fat/p-S",
        "Fat/~-›",
        "Fat9",
        "FatiZlatieres Grasses",
        "Fatl",
        "Fett",
        "Fett / fat / matières grasses, grasas / Amapá",
        "Fett / fat / matières grusses, grasas / Amapá",
        "Fett / matières grasses I grassi",
        "Fett / matières sses / grassi",
        "Fett graisses / vetten / fat / grassi grasas fedt:",
        "Fett grasses / vetten / fat / grassi grasas fedt:",
        "Fett/",
        "Fett/matières sses/grassi",
        "Fettsauren",
        "Fo&1 Kalslum Fosfat), Itamln (83, 86, 812],",
        "Freshn6ssgtharanl8erfuTrlllpilTrl4d rfatsorlh1$5Tr3ck's",
        "G Ingredients: Beef meat, beef fat, nitrite salt (salt, presemative: sodium nitite),",
        "Grasa Saturada Sat Fat",
        "Grasa Saturada/Sat Fat Menos de/Less than 20g",
        "Grasa Total / Total Fat",
        "Grasa Total / Total Fat 8g",
        "Grasa Total/Total Fata",
        "Grasa Total/Total Fate",
        "Grasa Total/Total Pa",
        "Grasa TotalTolal Pa",
        "Grasa total",
        "Grasa total i- ¥ ..",
        "Grasa/Fat 9",
        "Grasimi",
        "Gräsimi",
        "Grnsa Total l Total Fat 8g",
        "Grosa Fat 9 • Carbohidratos/Carbohydrate. 4 • Proteína/Protein",
        "HERBANS. KONA YOGURT (CULTURED PASTEURIZED NONFAT MILK. LIVE AND ACTIVE CULLE,",
        "IFett I Vetten / Grassi IGrasas",
        "IFett/ Vetten / Grassi l Grasas",
        "INGREDIENTS. CREAM, NONFAI *13a",
        "INGREDIENTS.. CULTURED GRADE A NON FAT MILK CHICORY ROOT FI8ER,",
        "INGREDIENTS: Low Fat Yogurt, Sugar, Raspberry Purée (2.5%)",
        "INGREDIENTS: Low Fat Yogurt, Sugar, Raspherry Purée (2.5%)",
        "INGREDIENTS: Pasteurized recombined low fat milk drink (90%, feast",
        "INGREDIERITS: Pastaurized recombined low fat milk drik (9o%) fs",
        "J CaTbohydrate1Jw￿G1UthjesI HldfatosdecaTbono 5.69",
        "Jumlah Lemak l Total Fat O,O g",
        "KrnkTDt•l l TotalFat",
        "LarnakTotal l Total Fat",
        "Lemak Total / Total Fat",
        "Lípidos (g)",
        "L•fflakTotsl l Trtal Fat",
        "L•makTotsl l Total Fat",
        "L•m•kTotsl l Total Fat",
        "MARIGOLD Low Fat Natural Voghurt",
        "MARIGOLD Non Fat Peach and Mango Yoghurt",
        "Matières grasses ' Fett",
        "Matières grasses 'Fett",
        "Matières grasses l Fett",
        "Monounsaluraled Fat 2g",
        "Of Which Satuiates / Dont acides 9ras saturés l Davon g.esattigte Fettsauren I",
        "Per Pot 116 Calories 2.2g Fat",
        "Per Pot 116 Calories 2.2g Fat its*iti:",
        "Polyunsaiurated Fat Og",
        "Refri9efate after openln9 and",
        "Rinderfleischfett, Nitritpökelsalz",
        "Sai Fai",
        "Sat Fat",
        "Sat Fat 40",
        "Sat Fat 4g",
        "Sat Fat Less than 20g",
        "Sat Fat Less than ?og",
        "TMS Fat Og",
        "Tauszcz Riebalai/Grasime/Fat",
        "Tauszcz/Riebalai/Grasime/Fat",
        "Tffins Fat Og",
        "ThJszcthiebaJadGrasimelFat",
        "The Beerenberg Fail 14.,",
        "Tians Fatty Acids (g)",
        "Tina veget31e [grassi e oli vegetali",
        "Tmns Fat Og",
        "Tmns Fats",
        "Toial Fai",
        "Tolal Fat 11 g",
        "Tot81 Fat 3g",
        "Total Fat",
        "Total Fat ()J",
        "Total Fat (g)",
        "Total Fat /",
        "Total Fat / ¿saull cyana",
        "Total Fat / ¿saull cyaza",
        "Total Fat / Fett Fedt",
        "Total Fat / Fett/ Fedt",
        "Total Fat / Grasa Total 8g",
        "Total Fat / üsaull cyaza",
        "Total Fat / üssull cyaza",
        "Total Fat 0.2 g",
        "Total Fat 0.5g",
        "Total Fat 0g",
        "Total Fat 1",
        "Total Fat 10g",
        "Total Fat 11 g",
        "Total Fat 12g",
        "Total Fat 14g",
        "Total Fat 16g",
        "Total Fat 17g",
        "Total Fat 2.5g",
        "Total Fat 3",
        "Total Fat 3g",
        "Total Fat 4g",
        "Total Fat 6g",
        "Total Fat 7g",
        "Total Fat JosillEgazA",
        "Total Fat Jysill Egaz",
        "Total Fat Less than 65g",
        "Total Fat Less tt",
        "Total Fat Og",
        "Total Fat g",
        "Total Fat l Grasa Total 8g",
        "Total Fat o.sg",
        "Total Fat/ Graisse Totale",
        "Total Fat/ Graisse Totale 0 g",
        "Total Fat/ Total des lipides 0 g",
        "Total Fat/Grasa Total 1 g",
        "Total Fat/Grasa Total 1g",
        "Total Fat/Jumlah lemak/8 RE R",
        "Total Fat/Jumlah lemak/N ME Ro",
        "Total Fat1 Og",
        "Total FatlJumlah lernak1xA￿Kts",
        "Total FauGrasa Total 1 g",
        "Total fat 9",
        "Total fat 9g",
        "Total fat/",
        "Total fat/ 03.0 all -las!/ Matières grasses totales/",
        "Total fat/ 030ll -llas!/ Matières grasses totales/",
        "Total fat/ 090 all -JLas!/ Matières grasses totales/",
        "Total fat/ 095 All g-lLa-!/ Matières grasses totales/",
        "Total fat/ 095ul gJLaa!/ Matières grasses totales/",
        "Total fat/ 09o all -las!/ Matières grasses totales/",
        "Total fat/ 09oall -JLas!/ Matières grasses totales/",
        "Total fat/ 09oall Hlas!/ Matières grasses totales/",
        "Total fat/ 0souJl -JLas!/ Matières grasses totales/",
        "Total fat/ 110 all -Las!/ Matières grasses totales/",
        "Total fat/ 110ull -Las!/ Matières grasses totales/",
        "Total fat/ 39 all -Jas!/ Matières grasses totales/",
        "Total fat/ 3gull Jlas!/ Matières grasses totales/",
        "Total fat/ 3pul Jas!/ Matières grasses totales/",
        "Total fat/ Jpu JJlas!/ Matières grasses totales/",
        "Total fat/ U,soul gallos !/ Matières grasses totales/",
        "Total fat/ Usol gJlas!/ Matières grasses totales/",
        "Total fat/ WIL￿. l/ Matières grasses totalesl",
        "Total fat/ ooo all -lLas!/ Matières grasses totales/",
        "Total fat/ osaall -Laa!/ Matières grasses totales/",
        "Total fat/ osoall -JLaa/ Matières grasses totales/",
        "Total fat/Matières grasses/",
        "Total fatj a9￿1 Matières grasses totalesl",
        "Totsl Fat",
        "Totsl Fat 179",
        "Totsl Fat 7g",
        "Totsl fat/Makn grasses/",
        "Totsl fatl èLyJ Mqtlères grasses totslesl",
        "Tot•1 Fat 2.93",
        "Tran8 Fat Og",
        "Tr￿S Fato g",
        "Tr￿Zc￿eballlGraSIMeffat",
        "Tuszcz/Riebalai/Grasime/Fat",
        "T￿1 Fat",
        "T•tal Fat",
        "UARIGOLD Low Fat Netural Voghurt",
        "Voghurt produt with 5% blueberries, 5% fat| Jfaiba Sd ipasZeya",
        "Waarvan verzadigde vetzuren / di cui acidi grassi",
        "Waarvan verzadigde vetzuren / dí cui acidi grassi",
        "Waarvan verzadigde vetzuren / di cui acidi grassi di",
        "Yoghurt produt with 5% blueberries, 5% fat| Jab uS dispas/eye",
        "Zufaten:",
        "[ts￿Fat fyj",
        "a 1 euros Fat",
        "a Total ITotsl Fat 8g",
        "ant - mattat fett/ M￿tte .",
        "anzliche Fette und Ole",
        "atières GrasseslFett / Vetten / Grassi l Grasas",
        "atières GrasseslFett/ Vetten / Grassi l Grasas",
        "be fat (palm kernel oil), glazine",
        "ble fat (palm kernel oil), glazine",
        "c8iories 130 Galories from Fai 25",
        "cater son in stat / father de dolma), come crania ta",
        "esfrom Fat O",
        "fat (pafvn lemel oll), glazknl",
        "fatp",
        "fflakTotsl l Trtal Fat",
        "from Fat",
        "i Fat l Groas",
        "i grassi. salel, umidificante: soibitolo, fibra ve&NZA LATtO",
        "iotal Fat/ Total Iipides O g",
        "l*I Fat 16g",
        "l*frThn Fat o",
        "len l Grassi l Grasas",
        "mättat fett / mættet fedt",
        "mfy9b.Mrtp￿wtr ￿1th 5% blueberries, 5% fat JJL SdLI￿/jj.iI",
        "n&iluLknOffln\".Tr144 ( & rans fat) O n. (o)",
        "otal fat/ &)wll",
        "rNszcbfiiebalarfGrasime/Fat",
        "raisses / vellen / fat / rassi /",
        "rated Fat 7g",
        "te Fettsau",
    ],
    
    //MARK: - Saturated Fat
    .saturatedFat: [
        "¥qkn.￿lI1￿jj Saturated Fat Og",
        "(),!.which saturates/",
        "- Of Which Saturates / Dont acides gras saturés / Davon gesättigte Fettsäuren /",
        "- Of Which Saturates / Dont acides gras saturés / Davon gesättigte Fettsäuren/",
        "- Of Which Saturates l Dont acides gras saturés l Davon gesattigte Fettsa'uren I",
        "- SATURATED",
        "- Saturated/ Satures",
        "- Saturated/ Satures O g",
        "- knunsaturated faty acids/Lemak",
        "- of which saturates/L: 4 Ad",
        "-SATURATED",
        "-of which saturates/",
        "-of which saturates/ 14- Asstall 395 All Umay",
        "-of which saturates/ 1g. astutell ops all dues/",
        "-of which saturates/ 1gu Asutall 395ll a",
        "-of which saturates/ 1gu astell ogoaJl dus/",
        "-of which saturates/ 1gu astull 095all Loms/",
        "-of which saturates/ Lay artill opal aus/",
        "-of which saturates/ Lg astill op all aus/",
        "-of which saturates/ Lg1 as elull pas all dates/",
        "-of which saturates/ Lg4 Mantull 095 all coms/",
        "-of which saturates/ Lgr ärelull ogsall duuts/",
        "-of which saturates/ Lgr ärsutull og0all auus/",
        "-of which saturates/ Lgr arutull ogall auus/",
        "-of which saturates/ la- arutall gpsall dums/",
        "-of which saturates/ lgr äruhall gysall dums/",
        "-of which saturates/L6:4aAd",
        "-of whlch saturates/",
        "-of whlch saturates/ L+.",
        "-of wliich saturates/ L6J.",
        "-ofwhich saturateS/LéJd￿a￿1",
        "-ofwhlch saturates/",
        "-ofwhlch saturates/ 4￿￿11",
        ". SATUR4TED",
        ".SATURATED",
        ".of yhlch saturates/",
        "Amount per serving Saturated Fat Sugars Total Fat 3g Trans Fat 0g Sodium 380mg Incl. 0g Added",
        "At least 2% lower in saturated fat compared to regular yoghurt",
        "At least 2y lower in saturated fat compared to regularyoghart",
        "Cering Saer: Goz (170g) Saturated Fat",
        "Coring, Sae: Goz (170g) Saturated Fat",
        "Gigsa Saluiadal Satulaled Fal 19",
        "Grasa Saturada / Saturated Fat 1g",
        "Indudlurto (Saturatad fal) 1 n. (g)",
        "Lemak Jenuh / Saturated Fat",
        "Lemak Jenuh / Saturated Fot",
        "Lemak Jenuh /SaturatedFat",
        "Lemak Jenuh I Saturated Fa",
        "Lemak Jenuh Saturated Fat",
        "Lemakjenuh I Saturated Far",
        "Lemat Jenuh/ Saturated Fat",
        "Lemat Jenwh/ Saturated Fat",
        "Lernakjenuh I Saturated Fat",
        "Let which Saturates/p",
        "M('iounsaturated Fat 1 g",
        "Of Which Saturates / Dont acides 9ras saturés l Davon g.esattigte Fettsauren I",
        "Of Which Saturates / Dont acides aras saturés / Davon gesättigte Fettsäuren /",
        "Of Which Saturates / Dont acides gras saturés / Davon gesättigte Fettsäuren /",
        "Of Which Saturates / Dont acides gras saturés / Davon gesättigte Fettsäuren/",
        "Of Which Saturates / Dont acides gras satures l Davon g.esattigte Fettsauren I",
        "Of Which Saturates /Dont acides gras saturés / Davon gesättigte Fettsäuren /",
        "Of Which Saturates /Dont acides gras saturés / Davon gesättigte Fettsäuren/",
        "Of Which Saturates l Dont acides gras saturés l Davon qesattigte Fettsauren I",
        "Of Which Saturates/ Dont acides gras satures / Davon g.esattigte Fettsauren I",
        "Of Which Saturates/ Dont acides gras saturés / Davon gesättigte Fettsäuren /",
        "Of Which Saturates/Dont acides 9ras satures l Davon qesattigte Fettsauren I",
        "Of Which Saturates/Dont acides gras satures / Davon g.esattigte Fettsauren I",
        "Of Which Saturates/Dont acides gras satures l Davon qesattigte Fettsauren I",
        "Po Junsaturated Fat Og",
        "Po vunsaturated Fat",
        "SATUP.ATED",
        "SATUP.ITED",
        "SATURATED",
        "SATURATED / SATURÉES",
        "SATURATED / SATURÉES 4.8g",
        "Sat. Fat",
        "Sat. fat 4.5",
        "Sat. fat 4.5g",
        "SatuTrted FalfyJ K htsl CJhh*ats19g 6%",
        "Saturaled Fal",
        "Saturated",
        "Saturated / saturés 0 g",
        "Saturated / saturés 9 g",
        "Saturated / saturés O g",
        "Saturated FaUGrasa Saturada Og",
        "Saturated Fal Og",
        "Saturated Fat",
        "Saturated Fat (g)",
        "Saturated Fat / Grasa Saturada 1g",
        "Saturated Fat / Grasa Saturada lg",
        "Saturated Fat 0 g",
        "Saturated Fat 0.5",
        "Saturated Fat 0.5g",
        "Saturated Fat 0g",
        "Saturated Fat 0g 0% Total Carbohydrate 15g 5%",
        "Saturated Fat 1,5g",
        "Saturated Fat 1.5g",
        "Saturated Fat 13g",
        "Saturated Fat 2g",
        "Saturated Fat 4.5g",
        "Saturated Fat 6g",
        "Saturated Fat 6g 30 %",
        "Saturated Fat 7 g",
        "Saturated Fat 7g",
        "Saturated Fat C",
        "Saturated Fat O",
        "Saturated Fat Og",
        "Saturated Fat g",
        "Saturated Fat o",
        "Saturated Fat/Grasa Saturada 0g",
        "Saturated Fats",
        "Saturated Fats 0,03",
        "Saturated Fatty Acids (g)",
        "Saturated I saturés 9 g",
        "Saturated Less than1g Less than1g",
        "Saturated fat",
        "Saturated fat /",
        "Saturated fat / 2a ad 1 09 ul",
        "Saturated fat / 2auad1 0gJl",
        "Saturated fat / 2aual 95sul",
        "Saturated fat / ¿anal 95 ul",
        "Saturated fat /&&al i￿￿1",
        "Saturated fat 0 g",
        "Saturated fat O g",
        "Saturated fat i￿￿1",
        "Saturated fatty acids/Lemak tepu/",
        "Saturated/ Saturés",
        "Saturated/ Saturés 0 g",
        "Saturatfrd Fat O",
        "Saturatod Fat OJ",
        "Saturdted Fats 0,03",
        "Total saturated fat content not more than 7.99% by weight.",
        "V pm kwasy nasycone/is kuru sociosios/din",
        "Vym kwasy nasycone/is kuriu sociosios/din",
        "W/tum kvasy nasyconefis kuriy sociosios/din",
        "W/tum kwasy nasycone/is kuriy sociosios/din",
        "Waarvan verzadigde vetzuren / di cui acidi grassi saturi / De las cuales: Saturadas",
        "Waarvan verzadigde vetzuren / dí cui acidi grassi saturi / De las cuales: Saturadas",
        "Waarvan verzadigde vetzuren di cui acidi grassi saturi / De las cuales: Saturadas",
        "Waarvan verzadigde vetzuren dí cui acidi grassi saturi / De las cuales: Saturadas",
        "Waarvan verzadiqde vetzuren / di cui acidi grassi saturi / De las cuales: Saturadas",
        "Wtym kvasy nasyconefis kuriy sociosios/din",
        "Wtym kwasy nasyconefis kuriy sociosios/din",
        "care saturate/ of which saturates.",
        "davon gesattigte",
        "davon gesättigte",
        "davon gesättigte Fettsäuren / dont acides gras saturés / di cui acidi grassi saturi",
        "davon gesättigte Fettsäuren / dont acides gras saturés / waarvan",
        "davon gesättigte Fettsäuren / dont acides gras saturés / waavan",
        "davon gesättigte Fettsäuren of which saturates /",
        "davon gesättigte Fettsäuren y of which saturates /",
        "de las cuales ácidos grasos saturados heraf mattede fedtsyrer: 16 g",
        "de las cuales ácidos grass saturados heraf mattede fedtsyrer: 16 g",
        "df vhich saturates / dont acides",
        "df which saturates /",
        "din care acizi grasi saturati",
        "dont acides gras saturés / davon gesättigte Fettsäuren",
        "dont acides gras saturés / de las cuales saturadas /",
        "dont acides gras saturés / de las cuales saturadas/",
        "dont acides gras saturés/",
        "dont acides gras saturés/ de",
        "dont acides gras saturés/ de las cuales saturadas",
        "dont aclde5 gras saturés/ de las cuales sa¢uradas",
        "dont acldes gras saturésl de las cuales s(turadas",
        "dont acldes gras saturésl de las cuales saturadas",
        "dont addes gras saturésl de ks cuales situradas",
        "dontacides gras saturés/ de las cuales saturadas",
        "doritacldes gras saturés/ de las cuales saturadas",
        "dos quab saturados (g)",
        "dos quais saturados (g)",
        "dos quals saturados (g)",
        "dudlurto (Saturatad fal) 1 n. (g)",
        "f which saturatesl",
        "gesattigte Fettsauren / dontacides grds saturés I di cui aadi grassi saturi",
        "gras saturés / waarvan verladlgd",
        "gras saturés / waarvan verzadigd",
        "gras saturés / waarvan ve￿adlgd",
        "gras satures I waaNan ve￿adlgd",
        "gras saturés waarvan verzadigd",
        "n care acizi grasi saturati",
        "n cre acizi grasi saturati",
        "of vthkh saturated fatl",
        "of which Saturates/ 22 41",
        "of which Saturates/ 2a a u/ tes",
        "of which Saturates/ 2a, All Ais",
        "of which Saturates/ 2a. if lass",
        "of which Saturates/241",
        "of which Saturates/2a. yl lass",
        "of which Saturates/2e su tss",
        "of which Saturates/2s Ail lia",
        "of which Saturates/2sAsl laia",
        "of which Saturates/Aesal taua",
        "of which Saturates/Asl tata",
        "of which Saturates/Za, Agl Aia",
        "of which Saturatesl&L￿• 11",
        "of which saturated fat/",
        "of which saturates",
        "of which saturates /",
        "of which saturates / dont acides",
        "of which saturates dont acides",
        "of which saturates.",
        "of which saturates/",
        "of which saturates/*￿1 ' .",
        "of whkh saturated fav",
        "ol which saturates",
        "rasos saturados / hetaf m&ttede fedts",
        "rassi saturi l De las cuales. Saturadas",
        "rassi saturi l De las cuales: Saturadas",
        "sa Saturada I Saturated Fat1 g",
        "saturated",
        "saturated 7.4 g",
        "saturated Fat 1 ,5g",
        "saturi / De las cuales: Saturadas",
        "satur￿ed Fat",
        "verzadigde vetzuren / of which saturates di cui acidi grassi saturi/",
        "vetzadigde velzuren / of which saturates Idi cui acidi grassi saluti/",
        "we saturatel of which saturates,",
        "which saturates /",
        "• Of Which Saturates / Dont acides gras saturés / Davon gesättigte Fettsäuren /",
        "• Of Which Saturates / Dont acides gras saturés / Davon gesättigte Fettsäuren/",
        "• Saturated",
        "• Saturated Sa:",
        "• Saturated Saa:",
        "• Saturated Sara:",
        "• saturated",
        "• saturated gesättigte Fettsäuren 3.2 g",
    ],
    
    //MARK: - Polyunsaturated Fat
    .polyunsaturatedFat: [
        
    ],
]
