import XCTest

@testable import NutritionLabelClassifier

final class AttributeFatTests: XCTestCase {

    func testAttributeFat() throws {
        for testCase in validCases {
            XCTAssertTrue(Attribute.detect(in: testCase).contains(.fat), "\(testCase) failed to be recognized as containing fat")
        }
        
        for testCase in invalidCases {
            XCTAssertFalse(Attribute.detect(in: testCase).contains(.fat), "\(testCase) incorrectly recognized as containing fat")
        }
    }
    
    let validCases = [
        "',%l Total Fat Og",
        "(GB) Mild white Cheddar cheese, 35 % total fat, 48% f.l.d.m.,",
        "(GB) Mild white Cheddar cheese, 35% total fat, 48% f.i.d.m.,",
        "(Modified starch), Milkfat, Beef gelatin, Sweetener (Sucralosel), Fret real g",
        "(Palm, Sonnenblume), Wasser, mulgator.: Miono- und Dialyceride von Speisefettsauren; Saiz, Feuchthafemiel: Sorbito), pilanzliche Faser(Psyllium), sojaprotein, Reisstärke, Verdi-",
        "(lodiied starch), Milkfat, Beef gelatin, Sweetener (Sucralosel), Frot reag",
        "(palma, girasole), acqua, emulsionante: mono- e digliceridi degli acidi grassi, sale], umidificante: sorbitolo; fibra vegetale (psillio), proteine disoia, amido di riso, addensanti: gomma di",
        "- s&Urat￿ fatty acids/Lemak tepul",
        "/ Energie / En'er2Fett I Vetten l Grassi l Grasas",
        "/ Energie / EneriFett / Vetten / Grassi l Grasas",
        "/ Energie l Ener2Fett I Vetten l Grassi l Grasas",
        "0 % Total Fat Boule ta",
        "0% Total Fat Boale ta",
        "© Glutenfreier Tortilla-Wrap. Spezill formuliert für Menschen mit Glutenunverträglichkeit, ZUTATEN: Reis meh), Wasser, piflanzliche Margarine [pflanzliche Fette und Öle",
        "© Glutenfreier Tortilla-Wrap. Spezillformuliert für Menschen mit Glutenunverträglichkei t, ZUTATEN: Reis mehl, Wasser, piflanzliche Margarine [pflanzliche Fette und Öle",
        "© Tortilla-wrap senza glutine. Specificamente formulato per persone intolleranti al glutine. INGREDIENT: Farina di riso, acqua, margarina vegetale [grassi e oli vegetali",
        "© Tortilla-wrap senza glutine. Specificamente formulato per persone intolleranti al glutine. INGREDIENTI: Farina di riso, acqua, margarina vegetale [grassi e oli vegetali",
        "Cacries from Fat 0",
        "Calorfes 250 Calories from Fat 140",
        "Calories 130 Fat calories 80",
        "Calories 150 Calories from Fat 25",
        "Calories 250 Calories from Fat 140",
        "Calories from Fat 0",
        "Calories from Fat 0 Cholesterol <5mg 1% Sugars 7g",
        "Calories from Fat 25",
        "Calories130 Fat calories 80",
        "Calories150 Calories from Fat 25",
        "Clories from Fat O S•dlK• 50fflg",
        "ERANS. KONEA YOGURT (CULTURED PASTEURIZED NONFAT MILK LIVE AND ACTIVE CULLIE,",
        "ETheigy from Fat (kcal)",
        "ETheryl dadLemak l Energy from Fat",
        "Energi dari Lemak / Energy from Fat",
        "Energi dari Lemak / Eners gy from Fat",
        "Energi dari Lemak / Eners y from Fat",
        "Energi dari Lemak/ Energy from Fat",
        "Energl daTI Lemak l Energy from Fat",
        "Energl darf Lemak l Energy fmm Fat",
        "Energl darl Lemakl Enertyfrom Fat",
        "Energry from Fat",
        "Energy from Fat",
        "Energy from Fat (kcal)",
        "FAI",
        "FAT, TOTAL",
        "Fat",
        "Fat (0 g)",
        "Fat (O g)",
        "Fat (g)",
        "Fat / Lip,'des / Vetten",
        "Fat / Lipides / Vetten",
        "Fat / Lipides 0 g",
        "Fat / Lipides O g",
        "Fat / Matières Grasses / Fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses / Fett / Vetten / Grassi Grasas",
        "Fat / Matières Grasses / Fett Vetten / Grassi / Grasas",
        "Fat / Matières Grasses / fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses /Fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses /fett / Vetten / Grassi / Grasas",
        "Fat / Matières Grasses Fett / Vetten / Grassi / Grasas",
        "Fat /Matières Grasses /Fett / Vetten / Grassi / Grasas",
        "Fat /Matières Grasses /Fett Vetten / Grassi / Grasas",
        "Fat 9 Carbohydrate4 • Protein4",
        "Fat 9 • Carbohydrate 4 • Protein 4",
        "Fat I",
        "Fat, total",
        "Fat/",
        "Fat/ a",
        "Fat/&lP' ....................",
        "Fat/--›",
        "Fat/-›",
        "Fat/.-d3",
        "Fat/...43",
        "Fat/39.03 ................................",
        "Fat/Zlatieres Grasses",
        "Fat/aa",
        "Fat/e-s",
        "Fat/ee",
        "Fat/fvaJ",
        "Fat/j9... ................................",
        "Fat/o-S",
        "Fat/p-S",
        "Fat/~-›",
        "FatiZlatieres Grasses",
        "Fatl",
        "Fett / matières grasses I grassi",
        "Fett / matières sses / grassi",
        "Fett/matières sses/grassi",
        "Grasa total",
        "Grasa total i- ¥ ..",
        "Grasimi",
        "Gräsimi",
        "HERBANS. KONA YOGURT (CULTURED PASTEURIZED NONFAT MILK. LIVE AND ACTIVE CULLE,",
        "IFett I Vetten / Grassi IGrasas",
        "IFett/ Vetten / Grassi l Grasas",
        "INGREDIENTS. CREAM, NONFAI *13a",
        "INGREDIENTS.. CULTURED GRADE A NON FAT MILK CHICORY ROOT FI8ER,",
        "INGREDIENTS: CULTURED GRADE A NON FAT MILK, CHICORY ROOT FIBER,",
        "INGREDIENTS: CULTURED GRADE A NON FAT MILK, WATER, STRAWBERRY, SUGAR, FRUCTOSE, CONTAINS LESS THAN 1%",
        "INGREDIENTS: Low Fat Yogurt, Sugar, Raspberry Purée (2.5%)",
        "INGREDIENTS: Low Fat Yogurt, Sugar, Raspherry Purée (2.5%)",
        "INGREDIENTS: Pasteurized recombined low fat milk drink (90%, feast",
        "INGREDIERITS: Pastaurized recombined low fat milk drik (9o%) fs",
        "J CaTbohydrate1Jw￿G1UthjesI HldfatosdecaTbono 5.69",
        "KrnkTDt•l l TotalFat",
        "LarnakTotal l Total Fat",
        "Lemak Total / Total Fat",
        "Lípidos (g)",
        "L•fflakTotsl l Trtal Fat",
        "L•makTotsl l Total Fat",
        "L•m•kTotsl l Total Fat",
        "MARIGOLD Low Fat Natural Voghurt",
        "MARIGOLD Non Fat Peach and Mango Yoghurt",
        "Monounsaluraled Fat 2g",
        "Nutrition Facts INGREDIENTS: CREAM, NONFAT ML, EMMA",
        "Nutrition Facts INGREDIENTS: CREAM, NONFAT MLK, IEMLA",
        "Of Which Satuiates / Dont acides 9ras saturés l Davon g.esattigte Fettsauren I",
        "Per Pot 116 Calories 2.2g Fat",
        "Per Pot 116 Calories 2.2g Fat its*iti:",
        "Refri9efate after openln9 and",
        "Sai Fai",
        "Sat Fat",
        "TMS Fat Og",
        "Tauszcz Riebalai/Grasime/Fat",
        "Tauszcz/Riebalai/Grasime/Fat",
        "Tffins Fat Og",
        "ThJszcthiebaJadGrasimelFat",
        "The Beerenberg Fail 14.,",
        "Tians Fatty Acids (g)",
        "Tina veget31e [grassi e oli vegetali",
        "Tmns Fat Og",
        "Tmns Fats",
        "Toial Fai",
        "Tot81 Fat 3g",
        "Total Fat",
        "Total Fat ()J",
        "Total Fat (g)",
        "Total Fat /",
        "Total Fat / ¿saull cyana",
        "Total Fat / ¿saull cyaza",
        "Total Fat / Fett Fedt",
        "Total Fat / Fett/ Fedt",
        "Total Fat / üsaull cyaza",
        "Total Fat / üssull cyaza",
        "Total Fat 0.2 g",
        "Total Fat 0g",
        "Total Fat 16g",
        "Total Fat 17g",
        "Total Fat 2.5g",
        "Total Fat 3",
        "Total Fat 3g",
        "Total Fat 4g",
        "Total Fat 7g",
        "Total Fat JosillEgazA",
        "Total Fat Jysill Egaz",
        "Total Fat Og",
        "Total Fat g",
        "Total Fat/ Graisse Totale",
        "Total Fat/ Graisse Totale 0 g",
        "Total Fat/ Total des lipides 0 g",
        "Total Fat/Grasa Total 1 g",
        "Total Fat/Grasa Total 1g",
        "Total Fat/Jumlah lemak/8 RE R",
        "Total Fat/Jumlah lemak/N ME Ro",
        "Total FatlJumlah lernak1xA￿Kts",
        "Total FauGrasa Total 1 g",
        "Total fat 9",
        "Total fat 9g",
        "Total fat/",
        "Total fat/ 03.0 all -las!/ Matières grasses totales/",
        "Total fat/ 030ll -llas!/ Matières grasses totales/",
        "Total fat/ 090 all -JLas!/ Matières grasses totales/",
        "Total fat/ 095 All g-lLa-!/ Matières grasses totales/",
        "Total fat/ 095ul gJLaa!/ Matières grasses totales/",
        "Total fat/ 09o all -las!/ Matières grasses totales/",
        "Total fat/ 09oall -JLas!/ Matières grasses totales/",
        "Total fat/ 09oall Hlas!/ Matières grasses totales/",
        "Total fat/ 0souJl -JLas!/ Matières grasses totales/",
        "Total fat/ 110 all -Las!/ Matières grasses totales/",
        "Total fat/ 110ull -Las!/ Matières grasses totales/",
        "Total fat/ 39 all -Jas!/ Matières grasses totales/",
        "Total fat/ 3gull Jlas!/ Matières grasses totales/",
        "Total fat/ 3pul Jas!/ Matières grasses totales/",
        "Total fat/ Jpu JJlas!/ Matières grasses totales/",
        "Total fat/ U,soul gallos !/ Matières grasses totales/",
        "Total fat/ Usol gJlas!/ Matières grasses totales/",
        "Total fat/ WIL￿. l/ Matières grasses totalesl",
        "Total fat/ ooo all -lLas!/ Matières grasses totales/",
        "Total fat/ osaall -Laa!/ Matières grasses totales/",
        "Total fat/ osoall -JLaa/ Matières grasses totales/",
        "Total fat/Matières grasses/",
        "Total fatj a9￿1 Matières grasses totalesl",
        "Totsl Fat",
        "Totsl Fat 179",
        "Totsl Fat 7g",
        "Totsl fat/Makn grasses/",
        "Totsl fatl èLyJ Mqtlères grasses totslesl",
        "Tot•1 Fat 2.93",
        "Tran8 Fat Og",
        "Tr￿Zc￿eballlGraSIMeffat",
        "Tuszcz/Riebalai/Grasime/Fat",
        "T￿1 Fat",
        "T•tal Fat",
        "UARIGOLD Low Fat Netural Voghurt",
        "Waarvan verzadigde vetzuren / di cui acidi grassi",
        "Waarvan verzadigde vetzuren / dí cui acidi grassi",
        "Waarvan verzadigde vetzuren / di cui acidi grassi di",
        "Y•s. IlQHFkT YOGURT (CULTURED PASTEURIZED NONFAT MILK, I IVE AND ACTIVE CUITUR5',",
        "[ts￿Fat fyj",
        "a 1 euros Fat",
        "ant - mattat fett/ M￿tte .",
        "anzliche Fette und Ole",
        "atières GrasseslFett / Vetten / Grassi l Grasas",
        "atières GrasseslFett/ Vetten / Grassi l Grasas",
        "be fat (palm kernel oil), glazine",
        "ble fat (palm kernel oil), glazine",
        "c8iories 130 Galories from Fai 25",
        "fat (pafvn lemel oll), glazknl",
        "fatp",
        "fflakTotsl l Trtal Fat",
        "from Fat",
        "i grassi. salel, umidificante: soibitolo, fibra ve&NZA LATtO",
        "iotal Fat/ Total Iipides O g",
        "l*I Fat 16g",
        "l*frThn Fat o",
        "len l Grassi l Grasas",
        "mättat fett / mættet fedt",
        "otal fat/ &)wll",
        "rNszcbfiiebalarfGrasime/Fat",
        "rated Fat 7g",
        "te Fettsau",
    ]
    
    let invalidCases = [
        "anufattured & Quality Tested by NOW FCWS.",
        "Saturatfrd Fat O",
        "Saturdted Fats 0,03",
        "satur￿ed Fat",
    ]
}

